/**
 * Edit this file to add your AI tools, knowledge items, and podcasts.
 * The site will automatically render all items from these arrays.
 *
 * Each item supports:
 *   title       — Name
 *   description — Short summary
 *   url         — Link (use "#" if none)
 *   tags        — Array of tags for search / filtering
 *   icon        — Emoji displayed on the poster cover
 *   color       — [from, to] hex pair for the poster gradient
 *   level       — Difficulty 1-10 (1 = beginner, 10 = world-class expert)
 */

const siteData = {
  tools: [
    {
      title: "ChatGPT",
      description: "Conversational AI for writing, coding, and brainstorming.",
      url: "https://chat.openai.com",
      tags: ["LLM", "Writing", "Coding"],
      icon: "\u{1F4AC}",
      color: ["#10a37f", "#1a7f5a"],
      level: 1,
    },
    {
      title: "Claude",
      description: "Anthropic's AI assistant for analysis and long-form content.",
      url: "https://claude.ai",
      tags: ["LLM", "Analysis", "Writing"],
      icon: "\u{1F9E0}",
      color: ["#cc785c", "#a0522d"],
      level: 1,
    },
    {
      title: "Cursor",
      description: "AI-powered code editor for faster development.",
      url: "https://cursor.com",
      tags: ["Coding", "IDE", "Productivity"],
      icon: "\u{1F4BB}",
      color: ["#7c3aed", "#4f46e5"],
      level: 3,
    },
    {
      title: "Midjourney",
      description: "Generate images from text prompts.",
      url: "https://midjourney.com",
      tags: ["Image", "Art", "Creative"],
      icon: "\u{1F3A8}",
      color: ["#e44d8a", "#b83280"],
      level: 2,
    },
    {
      title: "Perplexity",
      description: "AI search engine with cited answers.",
      url: "https://perplexity.ai",
      tags: ["Search", "Research", "Citations"],
      icon: "\u{1F50D}",
      color: ["#20b2aa", "#2980b9"],
      level: 1,
    },
  ],
  knowledge: [
    {
      title: "Prompt Engineering Basics",
      description: "How to write effective prompts for better AI responses.",
      url: "#",
      tags: ["Prompts", "Best Practices", "Getting Started"],
      icon: "\u{270F}\u{FE0F}",
      color: ["#f59e0b", "#d97706"],
      level: 2,
    },
    {
      title: "AI Ethics & Safety",
      description: "Understanding bias, transparency, and responsible AI use.",
      url: "#",
      tags: ["Ethics", "Safety", "Responsible AI"],
      icon: "\u{1F6E1}\u{FE0F}",
      color: ["#ef4444", "#b91c1c"],
      level: 3,
    },
    {
      title: "RAG Architecture Explained",
      description: "Retrieval-augmented generation for knowledge-grounded outputs.",
      url: "#",
      tags: ["RAG", "Architecture", "LLMs"],
      icon: "\u{1F9F1}",
      color: ["#6366f1", "#4338ca"],
      level: 6,
    },
  ],
  podcasts: [
    {
      title: "The AI Podcast (NVIDIA)",
      description: "NVIDIA's podcast featuring AI researchers and industry leaders.",
      url: "https://blogs.nvidia.com/ai-podcast/",
      tags: ["Interviews", "Research", "Industry"],
      icon: "\u{1F3D9}\u{FE0F}",
      color: ["#76b900", "#5a8f00"],
      level: 4,
    },
    {
      title: "Lex Fridman Podcast",
      description: "Deep dives into AI, science, and philosophy with top researchers.",
      url: "https://lexfridman.com/podcast/",
      tags: ["Interviews", "Philosophy", "AI"],
      icon: "\u{1F30C}",
      color: ["#8b5cf6", "#6d28d9"],
      level: 5,
    },
    {
      title: "Practical AI",
      description: "Making AI practical, productive, and accessible for everyone.",
      url: "https://changelog.com/practicalai",
      tags: ["Practical", "Productivity", "Tutorials"],
      icon: "\u{1F527}",
      color: ["#22c55e", "#16a34a"],
      level: 3,
    },
    {
      title: "Latent Space",
      description: "The podcast for AI engineers. Technical deep dives and founder interviews.",
      url: "https://www.latent.space/podcast",
      tags: ["Engineering", "Technical", "Startups"],
      icon: "\u{1F680}",
      color: ["#3b82f6", "#1d4ed8"],
      level: 7,
    },
    {
      title: "The TWIML AI Podcast",
      description: "This Week in Machine Learning & AI. Research and real-world applications.",
      url: "https://twimlai.com/podcast/",
      tags: ["ML", "Research", "Applications"],
      icon: "\u{1F4E1}",
      color: ["#0ea5e9", "#0369a1"],
      level: 6,
    },
    {
      title: "Eye on AI",
      description: "Craig S. Smith interviews AI leaders on what's coming next.",
      url: "https://www.eye-on.ai/podcast",
      tags: ["Interviews", "Future", "Leaders"],
      icon: "\u{1F441}\u{FE0F}",
      color: ["#f43f5e", "#be123c"],
      level: 4,
    },
    {
      title: "Machine Learning Street Talk",
      description: "In-depth technical discussions on ML research papers and concepts.",
      url: "https://www.youtube.com/@MachineLearningStreetTalk",
      tags: ["Research", "Papers", "Technical"],
      icon: "\u{1F9EA}",
      color: ["#a855f7", "#7e22ce"],
      level: 8,
    },
    {
      title: "Gradient Dissent",
      description: "Weights & Biases podcast with ML practitioners and researchers.",
      url: "https://wandb.ai/fully-connected/gradient-dissent",
      tags: ["MLOps", "Research", "Practitioners"],
      icon: "\u{1F4CA}",
      color: ["#f59e0b", "#b45309"],
      level: 7,
    },
  ],
  youtube: [
    {
      title: "Two Minute Papers",
      description: "AI research explained in short, visual, easy-to-follow videos.",
      url: "https://www.youtube.com/@TwoMinutePapers",
      tags: ["Research", "Visual", "Short"],
      icon: "\u{1F3AC}",
      color: ["#ef4444", "#b91c1c"],
      level: 3,
    },
    {
      title: "3Blue1Brown",
      description: "Beautiful math visualizations covering neural networks and ML concepts.",
      url: "https://www.youtube.com/@3blue1brown",
      tags: ["Math", "Visualizations", "Neural Networks"],
      icon: "\u{1F4D0}",
      color: ["#3b82f6", "#1e3a5f"],
      level: 4,
    },
    {
      title: "Andrej Karpathy",
      description: "Former Tesla AI director. Deep technical tutorials on building GPT from scratch.",
      url: "https://www.youtube.com/@AndrejKarpathy",
      tags: ["Technical", "GPT", "From Scratch"],
      icon: "\u{1F9D1}\u{200D}\u{1F4BB}",
      color: ["#6366f1", "#4338ca"],
      level: 7,
    },
    {
      title: "Yannic Kilcher",
      description: "ML paper reviews and explanations of cutting-edge AI research.",
      url: "https://www.youtube.com/@YannicKilcher",
      tags: ["Papers", "Research", "Reviews"],
      icon: "\u{1F4DD}",
      color: ["#14b8a6", "#0d9488"],
      level: 8,
    },
    {
      title: "Fireship",
      description: "Fast-paced dev content with excellent AI tool and concept explainers.",
      url: "https://www.youtube.com/@Fireship",
      tags: ["Dev", "Fast-Paced", "Tools"],
      icon: "\u{1F525}",
      color: ["#f97316", "#c2410c"],
      level: 2,
    },
    {
      title: "Matt Wolfe",
      description: "Weekly AI news roundups, tool reviews, and tutorials for creators.",
      url: "https://www.youtube.com/@maboroshi",
      tags: ["News", "Tools", "Tutorials"],
      icon: "\u{1F4F0}",
      color: ["#8b5cf6", "#5b21b6"],
      level: 2,
    },
    {
      title: "AI Explained",
      description: "Clear breakdowns of the latest AI models, benchmarks, and breakthroughs.",
      url: "https://www.youtube.com/@aiexplained-official",
      tags: ["Explainers", "Models", "Benchmarks"],
      icon: "\u{1F4A1}",
      color: ["#06b6d4", "#0e7490"],
      level: 4,
    },
    {
      title: "Sentdex",
      description: "Python and ML programming tutorials. Hands-on coding with real projects.",
      url: "https://www.youtube.com/@sentdex",
      tags: ["Python", "Coding", "Projects"],
      icon: "\u{1F40D}",
      color: ["#22c55e", "#15803d"],
      level: 5,
    },
  ],
  training: [
    {
      title: "DeepLearning.AI",
      description: "Andrew Ng's courses on deep learning, NLP, and generative AI.",
      url: "https://www.deeplearning.ai",
      tags: ["Courses", "Deep Learning", "Andrew Ng"],
      icon: "\u{1F393}",
      color: ["#0056d2", "#003d99"],
      level: 4,
    },
    {
      title: "fast.ai",
      description: "Practical deep learning for coders. Free, top-down approach.",
      url: "https://www.fast.ai",
      tags: ["Courses", "Deep Learning", "Free"],
      icon: "\u{26A1}",
      color: ["#6c3483", "#4a235a"],
      level: 5,
    },
    {
      title: "Coursera ML Specialization",
      description: "Stanford's machine learning specialization with Andrew Ng.",
      url: "https://www.coursera.org/specializations/machine-learning-introduction",
      tags: ["Courses", "ML", "Stanford"],
      icon: "\u{1F4D0}",
      color: ["#0056d2", "#2471a3"],
      level: 4,
    },
    {
      title: "HuggingFace Learn",
      description: "Open-source NLP courses, transformers, and model hub tutorials.",
      url: "https://huggingface.co/learn",
      tags: ["NLP", "Transformers", "Open Source"],
      icon: "\u{1F917}",
      color: ["#ffbd00", "#e6a800"],
      level: 6,
    },
    {
      title: "OpenAI Cookbook",
      description: "Example code and guides for using OpenAI APIs effectively.",
      url: "https://github.com/openai/openai-cookbook",
      tags: ["API", "Examples", "GPT"],
      icon: "\u{1F4D6}",
      color: ["#10a37f", "#0d8c6b"],
      level: 5,
    },
    {
      title: "Google AI Essentials",
      description: "Learn AI fundamentals and responsible AI from Google.",
      url: "https://grow.google/ai-essentials/",
      tags: ["Fundamentals", "Google", "Certification"],
      icon: "\u{1F310}",
      color: ["#4285f4", "#34a853"],
      level: 1,
    },
    {
      title: "Prompt Engineering Guide",
      description: "Comprehensive guide to prompt engineering techniques and research.",
      url: "https://www.promptingguide.ai",
      tags: ["Prompts", "Guide", "Techniques"],
      icon: "\u{1F9ED}",
      color: ["#f97316", "#ea580c"],
      level: 3,
    },
    {
      title: "LangChain Academy",
      description: "Build LLM-powered apps with LangChain. Structured learning paths.",
      url: "https://academy.langchain.com",
      tags: ["LangChain", "Agents", "RAG"],
      icon: "\u{1F517}",
      color: ["#1c3d5a", "#2d6a4f"],
      level: 7,
    },
  ],
};
