/**
 * Niche AI — Tools for taxes, home, travel, books, media, entertainment, sports
 * Each item supports: title, description, url, tags, icon, color, level (1-10)
 */

const nicheData = {
  taxes: [
    {
      title: "TurboTax AI Assist",
      description: "AI-powered tax preparation with smart deduction finder and filing help.",
      url: "https://turbotax.intuit.com",
      tags: ["Filing", "Deductions", "Self-Employed"],
      icon: "\u{1F4B8}",
      color: ["#2e7d32", "#1b5e20"],
      level: 1,
    },
    {
      title: "H&R Block AI Tax Advisor",
      description: "Get answers to tax questions and maximize refunds with AI guidance.",
      url: "https://www.hrblock.com",
      tags: ["Filing", "Advisor", "Refunds"],
      icon: "\u{1F4CA}",
      color: ["#1976d2", "#0d47a1"],
      level: 1,
    },
    {
      title: "April",
      description: "AI tax assistant for freelancers and self-employed. Automates deductions.",
      url: "https://www.getapril.com",
      tags: ["Freelance", "Automation", "Deductions"],
      icon: "\u{1F4DD}",
      color: ["#7c3aed", "#5b21b6"],
      level: 2,
    },
    {
      title: "TaxGPT",
      description: "Chat-based tax Q&A for understanding deductions, credits, and rules.",
      url: "https://taxgpt.ai",
      tags: ["Q&A", "Education", "Credits"],
      icon: "\u{1F4AC}",
      color: ["#0d9488", "#0f766e"],
      level: 1,
    },
    {
      title: "FlyFin",
      description: "AI finds and tracks tax deductions for freelancers automatically.",
      url: "https://www.flyfin.tax",
      tags: ["Freelance", "1099", "Expense Tracking"],
      icon: "\u{1F4B0}",
      color: ["#ea580c", "#c2410c"],
      level: 2,
    },
  ],
  home: [
    {
      title: "Reimagine Home",
      description: "AI interior design. Upload a photo and get redesign suggestions.",
      url: "https://reimaginehome.ai",
      tags: ["Interior", "Design", "Visualization"],
      icon: "\u{1F3E0}",
      color: ["#a855f7", "#7e22ce"],
      level: 1,
    },
    {
      title: "ChatGPT (Recipes)",
      description: "Generate meal plans, recipes, and shopping lists tailored to your pantry.",
      url: "https://chat.openai.com",
      tags: ["Recipes", "Meal Plans", "Cooking"],
      icon: "\u{1F372}",
      color: ["#10a37f", "#1a7f5a"],
      level: 1,
    },
    {
      title: "Amazon Alexa",
      description: "AI voice assistant for smart home control, routines, and automation.",
      url: "https://alexa.amazon.com",
      tags: ["Smart Home", "Voice", "Automation"],
      icon: "\u{1F4E1}",
      color: ["#00a8e1", "#0077b6"],
      level: 1,
    },
    {
      title: "Google Home",
      description: "Control lights, thermostats, and devices with AI voice commands.",
      url: "https://home.google.com",
      tags: ["Smart Home", "Nest", "Voice"],
      icon: "\u{1F4F1}",
      color: ["#4285f4", "#34a853"],
      level: 1,
    },
    {
      title: "Replicate (Home Models)",
      description: "Run image-to-design, room staging, and renovation AI models.",
      url: "https://replicate.com",
      tags: ["API", "Design", "Staging"],
      icon: "\u{1F3A8}",
      color: ["#6366f1", "#4f46e5"],
      level: 5,
    },
  ],
  travel: [
    {
      title: "ChatGPT Travel Planner",
      description: "Plan itineraries, get local tips, and tailor trips to your preferences.",
      url: "https://chat.openai.com",
      tags: ["Itineraries", "Tips", "Custom"],
      icon: "\u{1F30D}",
      color: ["#10a37f", "#1a7f5a"],
      level: 1,
    },
    {
      title: "Perplexity Travel",
      description: "Research destinations with cited sources. Weather, visas, hotels.",
      url: "https://perplexity.ai",
      tags: ["Research", "Cited", "Real-time"],
      icon: "\u{1F50D}",
      color: ["#20b2aa", "#2980b9"],
      level: 1,
    },
    {
      title: "Wanderlog",
      description: "AI-assisted trip planning. Import bookings and get day-by-day plans.",
      url: "https://wanderlog.com",
      tags: ["Itinerary", "Collaborative", "Maps"],
      icon: "\u{1F5FA}\u{FE0F}",
      color: ["#059669", "#047857"],
      level: 1,
    },
    {
      title: "Hopper",
      description: "AI predicts flight and hotel prices. Know when to book.",
      url: "https://www.hopper.com",
      tags: ["Predictions", "Deals", "Flights"],
      icon: "\u{2708}\u{FE0F}",
      color: ["#ec4899", "#db2777"],
      level: 1,
    },
    {
      title: "Layla (TripAdvisor)",
      description: "AI travel advisor for personalized recommendations and bookings.",
      url: "https://www.tripadvisor.com",
      tags: ["Recommendations", "Hotels", "Reviews"],
      icon: "\u{1F6CF}\u{FE0F}",
      color: ["#00aa6c", "#008556"],
      level: 1,
    },
    {
      title: "Kayak AI",
      description: "Smart search and price alerts. AI explains fare changes.",
      url: "https://www.kayak.com",
      tags: ["Flights", "Price Alerts", "Deals"],
      icon: "\u{1F4B5}",
      color: ["#f59e0b", "#d97706"],
      level: 1,
    },
  ],
  books: [
    {
      title: "ChatGPT Book Recs",
      description: "Get personalized book recommendations based on tastes and mood.",
      url: "https://chat.openai.com",
      tags: ["Recommendations", "Personalized", "Genres"],
      icon: "\u{1F4DA}",
      color: ["#10a37f", "#1a7f5a"],
      level: 1,
    },
    {
      title: "Audible Plus",
      description: "AI-narrated audiobooks. Thousands of titles with natural-sounding voices.",
      url: "https://www.audible.com",
      tags: ["Audiobooks", "AI Narration", "TTS"],
      icon: "\u{1F50A}",
      color: ["#f59e0b", "#b45309"],
      level: 1,
    },
    {
      title: "Blinkist",
      description: "AI-powered summaries of nonfiction books. 15-minute key takeaways.",
      url: "https://www.blinkist.com",
      tags: ["Summaries", "Nonfiction", "Speed Reading"],
      icon: "\u{1F4D6}",
      color: ["#3b82f6", "#1d4ed8"],
      level: 1,
    },
    {
      title: "Goodreads AI",
      description: "Personalized recommendations and reading challenges powered by ML.",
      url: "https://www.goodreads.com",
      tags: ["Recommendations", "Reviews", "Social"],
      icon: "\u{2764}\u{FE0F}",
      color: ["#553c9a", "#44337a"],
      level: 1,
    },
    {
      title: "Summarize.tech",
      description: "Summarize long articles and PDFs. Great for research and textbooks.",
      url: "https://www.summarize.tech",
      tags: ["Summaries", "PDF", "Research"],
      icon: "\u{1F4C4}",
      color: ["#0ea5e9", "#0284c7"],
      level: 2,
    },
    {
      title: "Google Play Books",
      description: "Read aloud, translate, and lookup definitions with AI assistance.",
      url: "https://play.google.com/books",
      tags: ["E-reader", "TTS", "Translation"],
      icon: "\u{1F4D5}",
      color: ["#4285f4", "#34a853"],
      level: 1,
    },
  ],
  media: [
    {
      title: "Descript",
      description: "Edit video and podcast by editing text. AI voices and transcription.",
      url: "https://www.descript.com",
      tags: ["Video", "Podcast", "Transcription"],
      icon: "\u{1F3AC}",
      color: ["#ec4899", "#be185d"],
      level: 3,
    },
    {
      title: "Runway",
      description: "AI video editing: green screen, motion tracking, and generative effects.",
      url: "https://runwayml.com",
      tags: ["Video", "VFX", "Generative"],
      icon: "\u{1F4F9}",
      color: ["#8b5cf6", "#6d28d9"],
      level: 4,
    },
    {
      title: "CapCut",
      description: "AI-powered cuts, captions, and effects for short-form video.",
      url: "https://www.capcut.com",
      tags: ["Video", "Short-form", "TikTok"],
      icon: "\u{1F4FA}",
      color: ["#ef4444", "#b91c1c"],
      level: 2,
    },
    {
      title: "Adobe Firefly",
      description: "Generate images, vectors, and edits. Ethical, licensed training.",
      url: "https://www.adobe.com/products/firefly.html",
      tags: ["Image", "Design", "Adobe"],
      icon: "\u{1F525}",
      color: ["#ff3366", "#cc2952"],
      level: 2,
    },
    {
      title: "Canva AI",
      description: "Magic Design, background removal, text-to-image for presentations.",
      url: "https://www.canva.com",
      tags: ["Design", "Templates", "Social"],
      icon: "\u{1F3A8}",
      color: ["#00c4cc", "#0099a0"],
      level: 1,
    },
    {
      title: "Luminar Neo",
      description: "AI photo editing: sky replacement, portrait enhancement, one-click fixes.",
      url: "https://skylum.com/luminar",
      tags: ["Photo", "Retouching", "Landscape"],
      icon: "\u{1F4F8}",
      color: ["#0ea5e9", "#0369a1"],
      level: 3,
    },
  ],
  entertainment: [
    {
      title: "Suno",
      description: "Create full songs from text prompts. AI music generation.",
      url: "https://suno.com",
      tags: ["Music", "Generation", "Songs"],
      icon: "\u{1F3B5}",
      color: ["#f97316", "#ea580c"],
      level: 1,
    },
    {
      title: "Udio",
      description: "AI music creation. Generate tracks in any style or genre.",
      url: "https://www.udio.com",
      tags: ["Music", "Generation", "Genres"],
      icon: "\u{1F3BA}",
      color: ["#6366f1", "#4f46e5"],
      level: 1,
    },
    {
      title: "ChatGPT Movie Recs",
      description: "Get movie and TV recommendations based on mood and preferences.",
      url: "https://chat.openai.com",
      tags: ["Movies", "TV", "Recommendations"],
      icon: "\u{1F3AC}",
      color: ["#10a37f", "#1a7f5a"],
      level: 1,
    },
    {
      title: "Midjourney",
      description: "Generate art for album covers, posters, and creative projects.",
      url: "https://midjourney.com",
      tags: ["Art", "Generation", "Creative"],
      icon: "\u{1F3A8}",
      color: ["#e44d8a", "#b83280"],
      level: 2,
    },
    {
      title: "Character.AI",
      description: "Chat with AI characters. Roleplay, storytelling, and fun.",
      url: "https://character.ai",
      tags: ["Chat", "Roleplay", "Characters"],
      icon: "\u{1F9DE}",
      color: ["#8b5cf6", "#7c3aed"],
      level: 1,
    },
    {
      title: "Inworld",
      description: "Create AI NPCs for games. Conversational, emotionally intelligent.",
      url: "https://www.inworld.ai",
      tags: ["Gaming", "NPCs", "Conversational"],
      icon: "\u{1F3AE}",
      color: ["#06b6d4", "#0891b2"],
      level: 5,
    },
  ],
  sports: [
    {
      title: "ChatGPT Sports Analysis",
      description: "Get stats, predictions, and breakdowns. Fantasy and betting insights.",
      url: "https://chat.openai.com",
      tags: ["Analysis", "Stats", "Fantasy"],
      icon: "\u{26BD}",
      color: ["#10a37f", "#1a7f5a"],
      level: 1,
    },
    {
      title: "ESPN Fantasy",
      description: "AI-powered projections, lineup optimizers, and waiver suggestions.",
      url: "https://fantasy.espn.com",
      tags: ["Fantasy", "Football", "Basketball"],
      icon: "\u{1F3C8}",
      color: ["#dc2626", "#b91c1c"],
      level: 2,
    },
    {
      title: "Sportradar",
      description: "AI analytics for live betting, player tracking, and performance.",
      url: "https://sportradar.com",
      tags: ["Analytics", "Betting", "Data"],
      icon: "\u{1F4CA}",
      color: ["#0d9488", "#0f766e"],
      level: 6,
    },
    {
      title: "Whoop",
      description: "AI recovery and strain analysis. Optimize training and sleep.",
      url: "https://www.whoop.com",
      tags: ["Fitness", "Recovery", "Wearable"],
      icon: "\u{1F3CB}\u{FE0F}",
      color: ["#000000", "#374151"],
      level: 2,
    },
    {
      title: "HomeCourt",
      description: "AI basketball trainer. Tracks shots, drills, and improvement over time.",
      url: "https://www.homecourt.ai",
      tags: ["Basketball", "Training", "Tracking"],
      icon: "\u{1F3C0}",
      color: ["#f59e0b", "#d97706"],
      level: 2,
    },
    {
      title: "Zwift",
      description: "AI-paced cycling and running. Virtual worlds and structured workouts.",
      url: "https://www.zwift.com",
      tags: ["Cycling", "Running", "Indoor"],
      icon: "\u{1F3C4}",
      color: ["#22c55e", "#16a34a"],
      level: 2,
    },
  ],
};
