/**
 * Niche AI — Tools for taxes, home, travel, books, media, entertainment, sports
 * Each item supports: title, description, url, tags, icon, color, level (1-10)
 */

const nicheData = {
  taxes: [
    {
      title: "TurboTax AI Assist",
      description: "AI-powered tax preparation with smart deduction finder and filing help.",
      url: "https://turbotax.intuit.com",
      tags: ["Filing", "Deductions", "Self-Employed"],
      icon: "\u{1F4B8}",
      color: ["#2e7d32", "#1b5e20"],
      level: 1,
    },
    {
      title: "H&R Block AI Tax Advisor",
      description: "Get answers to tax questions and maximize refunds with AI guidance.",
      url: "https://www.hrblock.com",
      tags: ["Filing", "Advisor", "Refunds"],
      icon: "\u{1F4CA}",
      color: ["#1976d2", "#0d47a1"],
      level: 1,
    },
    {
      title: "April",
      description: "AI tax assistant for freelancers and self-employed. Automates deductions.",
      url: "https://www.getapril.com",
      tags: ["Freelance", "Automation", "Deductions"],
      icon: "\u{1F4DD}",
      color: ["#7c3aed", "#5b21b6"],
      level: 2,
    },
    {
      title: "TaxGPT",
      description: "Chat-based tax Q&A for understanding deductions, credits, and rules.",
      url: "https://taxgpt.ai",
      tags: ["Q&A", "Education", "Credits"],
      icon: "\u{1F4AC}",
      color: ["#0d9488", "#0f766e"],
      level: 1,
    },
    {
      title: "FlyFin",
      description: "AI finds and tracks tax deductions for freelancers automatically.",
      url: "https://www.flyfin.tax",
      tags: ["Freelance", "1099", "Expense Tracking"],
      icon: "\u{1F4B0}",
      color: ["#ea580c", "#c2410c"],
      level: 2,
    },
    {
      title: "TaxAI 0",
      description: "AI filing helper for taxes enthusiasts and professionals.",
      url: "https://example.com/taxai 0",
      tags: ["Tax", "Tax"],
      icon: "💸",
      color: ["#ec4899", "#db2777"],
      level: 1,
    },
    {
      title: "DeductionBot 1",
      description: "AI tax advisor for taxes enthusiasts and professionals.",
      url: "https://example.com/deductionbot 1",
      tags: ["Tax", "Tax"],
      icon: "💸",
      color: ["#ec4899", "#db2777"],
      level: 1,
    },
    {
      title: "FilingAssist 2",
      description: "AI filing helper for taxes enthusiasts and professionals.",
      url: "https://example.com/filingassist 2",
      tags: ["Tax", "Filing"],
      icon: "💸",
      color: ["#00a8e1", "#0077b6"],
      level: 1,
    },
    {
      title: "FilingAssist 3",
      description: "AI tax advisor for taxes enthusiasts and professionals.",
      url: "https://example.com/filingassist 3",
      tags: ["Tax", "Filing"],
      icon: "💸",
      color: ["#ea580c", "#c2410c"],
      level: 4,
    },
    {
      title: "FilingAssist 4",
      description: "AI deduction finder for taxes enthusiasts and professionals.",
      url: "https://example.com/filingassist 4",
      tags: ["Tax", "Deductions"],
      icon: "💸",
      color: ["#059669", "#047857"],
      level: 2,
    },
    {
      title: "DeductionBot 5",
      description: "AI deduction finder for taxes enthusiasts and professionals.",
      url: "https://example.com/deductionbot 5",
      tags: ["Tax", "Tax"],
      icon: "💸",
      color: ["#059669", "#047857"],
      level: 2,
    },
    {
      title: "DeductionBot 6",
      description: "AI filing helper for taxes enthusiasts and professionals.",
      url: "https://example.com/deductionbot 6",
      tags: ["Filing", "Tax"],
      icon: "💸",
      color: ["#0d9488", "#0f766e"],
      level: 1,
    },
    {
      title: "TaxAI 7",
      description: "AI tax advisor for taxes enthusiasts and professionals.",
      url: "https://example.com/taxai 7",
      tags: ["Deductions", "Deductions"],
      icon: "💸",
      color: ["#0ea5e9", "#0284c7"],
      level: 3,
    },
    {
      title: "DeductionBot 8",
      description: "AI deduction finder for taxes enthusiasts and professionals.",
      url: "https://example.com/deductionbot 8",
      tags: ["Tax", "Tax"],
      icon: "💸",
      color: ["#ec4899", "#db2777"],
      level: 3,
    },
    {
      title: "TaxAI 9",
      description: "AI deduction finder for taxes enthusiasts and professionals.",
      url: "https://example.com/taxai 9",
      tags: ["Deductions", "Tax"],
      icon: "💸",
      color: ["#4285f4", "#34a853"],
      level: 2,
    },
    {
      title: "FilingAssist 10",
      description: "AI tax advisor for taxes enthusiasts and professionals.",
      url: "https://example.com/filingassist 10",
      tags: ["Tax", "Filing"],
      icon: "💸",
      color: ["#4285f4", "#34a853"],
      level: 2,
    },
    {
      title: "DeductionBot 11",
      description: "AI deduction finder for taxes enthusiasts and professionals.",
      url: "https://example.com/deductionbot 11",
      tags: ["Tax", "Filing"],
      icon: "💸",
      color: ["#7c3aed", "#5b21b6"],
      level: 3,
    },
    {
      title: "FilingAssist 12",
      description: "AI filing helper for taxes enthusiasts and professionals.",
      url: "https://example.com/filingassist 12",
      tags: ["Deductions", "Deductions"],
      icon: "💸",
      color: ["#1976d2", "#0d47a1"],
      level: 4,
    },
    {
      title: "DeductionBot 13",
      description: "AI filing helper for taxes enthusiasts and professionals.",
      url: "https://example.com/deductionbot 13",
      tags: ["Deductions", "Tax"],
      icon: "💸",
      color: ["#1976d2", "#0d47a1"],
      level: 4,
    },
    {
      title: "FilingAssist 14",
      description: "AI filing helper for taxes enthusiasts and professionals.",
      url: "https://example.com/filingassist 14",
      tags: ["Deductions", "Tax"],
      icon: "💸",
      color: ["#ec4899", "#db2777"],
      level: 3,
    },
    {
      title: "DeductionBot 15",
      description: "AI deduction finder for taxes enthusiasts and professionals.",
      url: "https://example.com/deductionbot 15",
      tags: ["Filing", "Filing"],
      icon: "💸",
      color: ["#ea580c", "#c2410c"],
      level: 3,
    },
    {
      title: "DeductionBot 16",
      description: "AI tax advisor for taxes enthusiasts and professionals.",
      url: "https://example.com/deductionbot 16",
      tags: ["Deductions", "Tax"],
      icon: "💸",
      color: ["#7c3aed", "#5b21b6"],
      level: 1,
    },
    {
      title: "TaxAI 17",
      description: "AI tax advisor for taxes enthusiasts and professionals.",
      url: "https://example.com/taxai 17",
      tags: ["Deductions", "Filing"],
      icon: "💸",
      color: ["#ea580c", "#c2410c"],
      level: 2,
    },
    {
      title: "TaxAI 18",
      description: "AI tax advisor for taxes enthusiasts and professionals.",
      url: "https://example.com/taxai 18",
      tags: ["Tax", "Filing"],
      icon: "💸",
      color: ["#a855f7", "#7e22ce"],
      level: 1,
    }

  ],
  home: [
    {
      title: "Reimagine Home",
      description: "AI interior design. Upload a photo and get redesign suggestions.",
      url: "https://reimaginehome.ai",
      tags: ["Interior", "Design", "Visualization"],
      icon: "\u{1F3E0}",
      color: ["#a855f7", "#7e22ce"],
      level: 1,
    },
    {
      title: "ChatGPT (Recipes)",
      description: "Generate meal plans, recipes, and shopping lists tailored to your pantry.",
      url: "https://chat.openai.com",
      tags: ["Recipes", "Meal Plans", "Cooking"],
      icon: "\u{1F372}",
      color: ["#10a37f", "#1a7f5a"],
      level: 1,
    },
    {
      title: "Amazon Alexa",
      description: "AI voice assistant for smart home control, routines, and automation.",
      url: "https://alexa.amazon.com",
      tags: ["Smart Home", "Voice", "Automation"],
      icon: "\u{1F4E1}",
      color: ["#00a8e1", "#0077b6"],
      level: 1,
    },
    {
      title: "Google Home",
      description: "Control lights, thermostats, and devices with AI voice commands.",
      url: "https://home.google.com",
      tags: ["Smart Home", "Nest", "Voice"],
      icon: "\u{1F4F1}",
      color: ["#4285f4", "#34a853"],
      level: 1,
    },
    {
      title: "Replicate (Home Models)",
      description: "Run image-to-design, room staging, and renovation AI models.",
      url: "https://replicate.com",
      tags: ["API", "Design", "Staging"],
      icon: "\u{1F3A8}",
      color: ["#6366f1", "#4f46e5"],
      level: 5,
    },
    {
      title: "DesignBot 0",
      description: "AI smart home for home enthusiasts and professionals.",
      url: "https://example.com/designbot 0",
      tags: ["Design", "Smart Home"],
      icon: "🏠",
      color: ["#4285f4", "#34a853"],
      level: 2,
    },
    {
      title: "SmartHome 1",
      description: "AI renovation planner for home enthusiasts and professionals.",
      url: "https://example.com/smarthome 1",
      tags: ["Design", "Home"],
      icon: "🏠",
      color: ["#a855f7", "#7e22ce"],
      level: 2,
    },
    {
      title: "SmartHome 2",
      description: "AI renovation planner for home enthusiasts and professionals.",
      url: "https://example.com/smarthome 2",
      tags: ["Home", "Design"],
      icon: "🏠",
      color: ["#00a8e1", "#0077b6"],
      level: 3,
    },
    {
      title: "DesignBot 3",
      description: "AI renovation planner for home enthusiasts and professionals.",
      url: "https://example.com/designbot 3",
      tags: ["Smart Home", "Design"],
      icon: "🏠",
      color: ["#059669", "#047857"],
      level: 2,
    },
    {
      title: "SmartHome 4",
      description: "AI renovation planner for home enthusiasts and professionals.",
      url: "https://example.com/smarthome 4",
      tags: ["Design", "Home"],
      icon: "🏠",
      color: ["#2e7d32", "#1b5e20"],
      level: 4,
    },
    {
      title: "DesignBot 5",
      description: "AI interior design for home enthusiasts and professionals.",
      url: "https://example.com/designbot 5",
      tags: ["Design", "Smart Home"],
      icon: "🏠",
      color: ["#7c3aed", "#5b21b6"],
      level: 2,
    },
    {
      title: "HomeAI 6",
      description: "AI interior design for home enthusiasts and professionals.",
      url: "https://example.com/homeai 6",
      tags: ["Design", "Smart Home"],
      icon: "🏠",
      color: ["#7c3aed", "#5b21b6"],
      level: 1,
    },
    {
      title: "DesignBot 7",
      description: "AI renovation planner for home enthusiasts and professionals.",
      url: "https://example.com/designbot 7",
      tags: ["Home", "Smart Home"],
      icon: "🏠",
      color: ["#ef4444", "#b91c1c"],
      level: 1,
    },
    {
      title: "HomeAI 8",
      description: "AI interior design for home enthusiasts and professionals.",
      url: "https://example.com/homeai 8",
      tags: ["Smart Home", "Smart Home"],
      icon: "🏠",
      color: ["#00a8e1", "#0077b6"],
      level: 1,
    },
    {
      title: "DesignBot 9",
      description: "AI smart home for home enthusiasts and professionals.",
      url: "https://example.com/designbot 9",
      tags: ["Smart Home", "Smart Home"],
      icon: "🏠",
      color: ["#ef4444", "#b91c1c"],
      level: 3,
    },
    {
      title: "SmartHome 10",
      description: "AI smart home for home enthusiasts and professionals.",
      url: "https://example.com/smarthome 10",
      tags: ["Design", "Smart Home"],
      icon: "🏠",
      color: ["#2e7d32", "#1b5e20"],
      level: 1,
    },
    {
      title: "SmartHome 11",
      description: "AI renovation planner for home enthusiasts and professionals.",
      url: "https://example.com/smarthome 11",
      tags: ["Home", "Design"],
      icon: "🏠",
      color: ["#1976d2", "#0d47a1"],
      level: 1,
    },
    {
      title: "DesignBot 12",
      description: "AI renovation planner for home enthusiasts and professionals.",
      url: "https://example.com/designbot 12",
      tags: ["Design", "Smart Home"],
      icon: "🏠",
      color: ["#0ea5e9", "#0284c7"],
      level: 4,
    },
    {
      title: "SmartHome 13",
      description: "AI smart home for home enthusiasts and professionals.",
      url: "https://example.com/smarthome 13",
      tags: ["Home", "Design"],
      icon: "🏠",
      color: ["#ef4444", "#b91c1c"],
      level: 2,
    },
    {
      title: "SmartHome 14",
      description: "AI interior design for home enthusiasts and professionals.",
      url: "https://example.com/smarthome 14",
      tags: ["Design", "Smart Home"],
      icon: "🏠",
      color: ["#a855f7", "#7e22ce"],
      level: 3,
    },
    {
      title: "HomeAI 15",
      description: "AI renovation planner for home enthusiasts and professionals.",
      url: "https://example.com/homeai 15",
      tags: ["Design", "Smart Home"],
      icon: "🏠",
      color: ["#ea580c", "#c2410c"],
      level: 4,
    },
    {
      title: "HomeAI 16",
      description: "AI interior design for home enthusiasts and professionals.",
      url: "https://example.com/homeai 16",
      tags: ["Design", "Home"],
      icon: "🏠",
      color: ["#2e7d32", "#1b5e20"],
      level: 1,
    },
    {
      title: "SmartHome 17",
      description: "AI renovation planner for home enthusiasts and professionals.",
      url: "https://example.com/smarthome 17",
      tags: ["Home", "Design"],
      icon: "🏠",
      color: ["#4285f4", "#34a853"],
      level: 4,
    },
    {
      title: "HomeAI 18",
      description: "AI smart home for home enthusiasts and professionals.",
      url: "https://example.com/homeai 18",
      tags: ["Smart Home", "Smart Home"],
      icon: "🏠",
      color: ["#7c3aed", "#5b21b6"],
      level: 1,
    }

  ],
  travel: [
    {
      title: "ChatGPT Travel Planner",
      description: "Plan itineraries, get local tips, and tailor trips to your preferences.",
      url: "https://chat.openai.com",
      tags: ["Itineraries", "Tips", "Custom"],
      icon: "\u{1F30D}",
      color: ["#10a37f", "#1a7f5a"],
      level: 1,
    },
    {
      title: "Perplexity Travel",
      description: "Research destinations with cited sources. Weather, visas, hotels.",
      url: "https://perplexity.ai",
      tags: ["Research", "Cited", "Real-time"],
      icon: "\u{1F50D}",
      color: ["#20b2aa", "#2980b9"],
      level: 1,
    },
    {
      title: "Wanderlog",
      description: "AI-assisted trip planning. Import bookings and get day-by-day plans.",
      url: "https://wanderlog.com",
      tags: ["Itinerary", "Collaborative", "Maps"],
      icon: "\u{1F5FA}\u{FE0F}",
      color: ["#059669", "#047857"],
      level: 1,
    },
    {
      title: "Hopper",
      description: "AI predicts flight and hotel prices. Know when to book.",
      url: "https://www.hopper.com",
      tags: ["Predictions", "Deals", "Flights"],
      icon: "\u{2708}\u{FE0F}",
      color: ["#ec4899", "#db2777"],
      level: 1,
    },
    {
      title: "Layla (TripAdvisor)",
      description: "AI travel advisor for personalized recommendations and bookings.",
      url: "https://www.tripadvisor.com",
      tags: ["Recommendations", "Hotels", "Reviews"],
      icon: "\u{1F6CF}\u{FE0F}",
      color: ["#00aa6c", "#008556"],
      level: 1,
    },
    {
      title: "Kayak AI",
      description: "Smart search and price alerts. AI explains fare changes.",
      url: "https://www.kayak.com",
      tags: ["Flights", "Price Alerts", "Deals"],
      icon: "\u{1F4B5}",
      color: ["#f59e0b", "#d97706"],
      level: 1,
    },
    {
      title: "WanderAssist 0",
      description: "AI booking helper for travel enthusiasts and professionals.",
      url: "https://example.com/wanderassist 0",
      tags: ["Travel", "Trips"],
      icon: "🌍",
      color: ["#059669", "#047857"],
      level: 3,
    },
    {
      title: "WanderAssist 1",
      description: "AI travel advisor for travel enthusiasts and professionals.",
      url: "https://example.com/wanderassist 1",
      tags: ["Travel", "Hotels"],
      icon: "🌍",
      color: ["#1976d2", "#0d47a1"],
      level: 4,
    },
    {
      title: "TripBot 2",
      description: "AI travel advisor for travel enthusiasts and professionals.",
      url: "https://example.com/tripbot 2",
      tags: ["Trips", "Trips"],
      icon: "🌍",
      color: ["#7c3aed", "#5b21b6"],
      level: 2,
    },
    {
      title: "WanderAssist 3",
      description: "AI itinerary planner for travel enthusiasts and professionals.",
      url: "https://example.com/wanderassist 3",
      tags: ["Trips", "Travel"],
      icon: "🌍",
      color: ["#ec4899", "#db2777"],
      level: 3,
    },
    {
      title: "WanderAssist 4",
      description: "AI booking helper for travel enthusiasts and professionals.",
      url: "https://example.com/wanderassist 4",
      tags: ["Trips", "Hotels"],
      icon: "🌍",
      color: ["#059669", "#047857"],
      level: 1,
    },
    {
      title: "WanderAssist 5",
      description: "AI itinerary planner for travel enthusiasts and professionals.",
      url: "https://example.com/wanderassist 5",
      tags: ["Travel", "Trips"],
      icon: "🌍",
      color: ["#1976d2", "#0d47a1"],
      level: 3,
    },
    {
      title: "WanderAssist 6",
      description: "AI itinerary planner for travel enthusiasts and professionals.",
      url: "https://example.com/wanderassist 6",
      tags: ["Hotels", "Travel"],
      icon: "🌍",
      color: ["#059669", "#047857"],
      level: 4,
    },
    {
      title: "TravelAI 7",
      description: "AI booking helper for travel enthusiasts and professionals.",
      url: "https://example.com/travelai 7",
      tags: ["Travel", "Hotels"],
      icon: "🌍",
      color: ["#ea580c", "#c2410c"],
      level: 3,
    },
    {
      title: "TravelAI 8",
      description: "AI booking helper for travel enthusiasts and professionals.",
      url: "https://example.com/travelai 8",
      tags: ["Trips", "Travel"],
      icon: "🌍",
      color: ["#ef4444", "#b91c1c"],
      level: 1,
    },
    {
      title: "TripBot 9",
      description: "AI itinerary planner for travel enthusiasts and professionals.",
      url: "https://example.com/tripbot 9",
      tags: ["Trips", "Travel"],
      icon: "🌍",
      color: ["#7c3aed", "#5b21b6"],
      level: 1,
    },
    {
      title: "WanderAssist 10",
      description: "AI itinerary planner for travel enthusiasts and professionals.",
      url: "https://example.com/wanderassist 10",
      tags: ["Hotels", "Hotels"],
      icon: "🌍",
      color: ["#00a8e1", "#0077b6"],
      level: 4,
    },
    {
      title: "TravelAI 11",
      description: "AI travel advisor for travel enthusiasts and professionals.",
      url: "https://example.com/travelai 11",
      tags: ["Travel", "Hotels"],
      icon: "🌍",
      color: ["#0ea5e9", "#0284c7"],
      level: 1,
    },
    {
      title: "WanderAssist 12",
      description: "AI booking helper for travel enthusiasts and professionals.",
      url: "https://example.com/wanderassist 12",
      tags: ["Travel", "Trips"],
      icon: "🌍",
      color: ["#a855f7", "#7e22ce"],
      level: 1,
    },
    {
      title: "WanderAssist 13",
      description: "AI booking helper for travel enthusiasts and professionals.",
      url: "https://example.com/wanderassist 13",
      tags: ["Hotels", "Trips"],
      icon: "🌍",
      color: ["#1976d2", "#0d47a1"],
      level: 4,
    },
    {
      title: "TravelAI 14",
      description: "AI itinerary planner for travel enthusiasts and professionals.",
      url: "https://example.com/travelai 14",
      tags: ["Travel", "Trips"],
      icon: "🌍",
      color: ["#7c3aed", "#5b21b6"],
      level: 3,
    },
    {
      title: "TravelAI 15",
      description: "AI booking helper for travel enthusiasts and professionals.",
      url: "https://example.com/travelai 15",
      tags: ["Trips", "Trips"],
      icon: "🌍",
      color: ["#ec4899", "#db2777"],
      level: 4,
    },
    {
      title: "TravelAI 16",
      description: "AI travel advisor for travel enthusiasts and professionals.",
      url: "https://example.com/travelai 16",
      tags: ["Travel", "Travel"],
      icon: "🌍",
      color: ["#00a8e1", "#0077b6"],
      level: 3,
    },
    {
      title: "WanderAssist 17",
      description: "AI travel advisor for travel enthusiasts and professionals.",
      url: "https://example.com/wanderassist 17",
      tags: ["Hotels", "Travel"],
      icon: "🌍",
      color: ["#2e7d32", "#1b5e20"],
      level: 1,
    },
    {
      title: "WanderAssist 18",
      description: "AI itinerary planner for travel enthusiasts and professionals.",
      url: "https://example.com/wanderassist 18",
      tags: ["Trips", "Trips"],
      icon: "🌍",
      color: ["#ec4899", "#db2777"],
      level: 2,
    }

  ],
  books: [
    {
      title: "ChatGPT Book Recs",
      description: "Get personalized book recommendations based on tastes and mood.",
      url: "https://chat.openai.com",
      tags: ["Recommendations", "Personalized", "Genres"],
      icon: "\u{1F4DA}",
      color: ["#10a37f", "#1a7f5a"],
      level: 1,
    },
    {
      title: "Audible Plus",
      description: "AI-narrated audiobooks. Thousands of titles with natural-sounding voices.",
      url: "https://www.audible.com",
      tags: ["Audiobooks", "AI Narration", "TTS"],
      icon: "\u{1F50A}",
      color: ["#f59e0b", "#b45309"],
      level: 1,
    },
    {
      title: "Blinkist",
      description: "AI-powered summaries of nonfiction books. 15-minute key takeaways.",
      url: "https://www.blinkist.com",
      tags: ["Summaries", "Nonfiction", "Speed Reading"],
      icon: "\u{1F4D6}",
      color: ["#3b82f6", "#1d4ed8"],
      level: 1,
    },
    {
      title: "Goodreads AI",
      description: "Personalized recommendations and reading challenges powered by ML.",
      url: "https://www.goodreads.com",
      tags: ["Recommendations", "Reviews", "Social"],
      icon: "\u{2764}\u{FE0F}",
      color: ["#553c9a", "#44337a"],
      level: 1,
    },
    {
      title: "Summarize.tech",
      description: "Summarize long articles and PDFs. Great for research and textbooks.",
      url: "https://www.summarize.tech",
      tags: ["Summaries", "PDF", "Research"],
      icon: "\u{1F4C4}",
      color: ["#0ea5e9", "#0284c7"],
      level: 2,
    },
    {
      title: "Google Play Books",
      description: "Read aloud, translate, and lookup definitions with AI assistance.",
      url: "https://play.google.com/books",
      tags: ["E-reader", "TTS", "Translation"],
      icon: "\u{1F4D5}",
      color: ["#4285f4", "#34a853"],
      level: 1,
    },
    {
      title: "ReadBot 0",
      description: "AI reading assistant for books enthusiasts and professionals.",
      url: "https://example.com/readbot 0",
      tags: ["Summaries", "Books"],
      icon: "📚",
      color: ["#4285f4", "#34a853"],
      level: 2,
    },
    {
      title: "BookAI 1",
      description: "AI book recommender for books enthusiasts and professionals.",
      url: "https://example.com/bookai 1",
      tags: ["Reading", "Summaries"],
      icon: "📚",
      color: ["#ef4444", "#b91c1c"],
      level: 1,
    },
    {
      title: "BookAI 2",
      description: "AI reading assistant for books enthusiasts and professionals.",
      url: "https://example.com/bookai 2",
      tags: ["Reading", "Summaries"],
      icon: "📚",
      color: ["#7c3aed", "#5b21b6"],
      level: 4,
    },
    {
      title: "SummarizePro 3",
      description: "AI reading assistant for books enthusiasts and professionals.",
      url: "https://example.com/summarizepro 3",
      tags: ["Books", "Summaries"],
      icon: "📚",
      color: ["#ea580c", "#c2410c"],
      level: 1,
    },
    {
      title: "SummarizePro 4",
      description: "AI book recommender for books enthusiasts and professionals.",
      url: "https://example.com/summarizepro 4",
      tags: ["Books", "Summaries"],
      icon: "📚",
      color: ["#1976d2", "#0d47a1"],
      level: 4,
    },
    {
      title: "SummarizePro 5",
      description: "AI summary generator for books enthusiasts and professionals.",
      url: "https://example.com/summarizepro 5",
      tags: ["Reading", "Books"],
      icon: "📚",
      color: ["#ea580c", "#c2410c"],
      level: 3,
    },
    {
      title: "BookAI 6",
      description: "AI book recommender for books enthusiasts and professionals.",
      url: "https://example.com/bookai 6",
      tags: ["Books", "Reading"],
      icon: "📚",
      color: ["#ef4444", "#b91c1c"],
      level: 1,
    },
    {
      title: "ReadBot 7",
      description: "AI book recommender for books enthusiasts and professionals.",
      url: "https://example.com/readbot 7",
      tags: ["Summaries", "Summaries"],
      icon: "📚",
      color: ["#0d9488", "#0f766e"],
      level: 3,
    },
    {
      title: "BookAI 8",
      description: "AI summary generator for books enthusiasts and professionals.",
      url: "https://example.com/bookai 8",
      tags: ["Summaries", "Reading"],
      icon: "📚",
      color: ["#059669", "#047857"],
      level: 2,
    },
    {
      title: "SummarizePro 9",
      description: "AI book recommender for books enthusiasts and professionals.",
      url: "https://example.com/summarizepro 9",
      tags: ["Books", "Summaries"],
      icon: "📚",
      color: ["#7c3aed", "#5b21b6"],
      level: 2,
    },
    {
      title: "BookAI 10",
      description: "AI reading assistant for books enthusiasts and professionals.",
      url: "https://example.com/bookai 10",
      tags: ["Books", "Summaries"],
      icon: "📚",
      color: ["#1976d2", "#0d47a1"],
      level: 4,
    },
    {
      title: "ReadBot 11",
      description: "AI reading assistant for books enthusiasts and professionals.",
      url: "https://example.com/readbot 11",
      tags: ["Books", "Books"],
      icon: "📚",
      color: ["#00a8e1", "#0077b6"],
      level: 1,
    },
    {
      title: "ReadBot 12",
      description: "AI book recommender for books enthusiasts and professionals.",
      url: "https://example.com/readbot 12",
      tags: ["Reading", "Reading"],
      icon: "📚",
      color: ["#2e7d32", "#1b5e20"],
      level: 3,
    },
    {
      title: "ReadBot 13",
      description: "AI summary generator for books enthusiasts and professionals.",
      url: "https://example.com/readbot 13",
      tags: ["Summaries", "Summaries"],
      icon: "📚",
      color: ["#ec4899", "#db2777"],
      level: 2,
    },
    {
      title: "ReadBot 14",
      description: "AI reading assistant for books enthusiasts and professionals.",
      url: "https://example.com/readbot 14",
      tags: ["Reading", "Reading"],
      icon: "📚",
      color: ["#7c3aed", "#5b21b6"],
      level: 2,
    },
    {
      title: "BookAI 15",
      description: "AI reading assistant for books enthusiasts and professionals.",
      url: "https://example.com/bookai 15",
      tags: ["Summaries", "Books"],
      icon: "📚",
      color: ["#0ea5e9", "#0284c7"],
      level: 1,
    },
    {
      title: "SummarizePro 16",
      description: "AI summary generator for books enthusiasts and professionals.",
      url: "https://example.com/summarizepro 16",
      tags: ["Summaries", "Reading"],
      icon: "📚",
      color: ["#1976d2", "#0d47a1"],
      level: 4,
    },
    {
      title: "ReadBot 17",
      description: "AI book recommender for books enthusiasts and professionals.",
      url: "https://example.com/readbot 17",
      tags: ["Books", "Books"],
      icon: "📚",
      color: ["#ef4444", "#b91c1c"],
      level: 4,
    },
    {
      title: "BookAI 18",
      description: "AI reading assistant for books enthusiasts and professionals.",
      url: "https://example.com/bookai 18",
      tags: ["Summaries", "Summaries"],
      icon: "📚",
      color: ["#0d9488", "#0f766e"],
      level: 3,
    }

  ],
  media: [
    {
      title: "Descript",
      description: "Edit video and podcast by editing text. AI voices and transcription.",
      url: "https://www.descript.com",
      tags: ["Video", "Podcast", "Transcription"],
      icon: "\u{1F3AC}",
      color: ["#ec4899", "#be185d"],
      level: 3,
    },
    {
      title: "Runway",
      description: "AI video editing: green screen, motion tracking, and generative effects.",
      url: "https://runwayml.com",
      tags: ["Video", "VFX", "Generative"],
      icon: "\u{1F4F9}",
      color: ["#8b5cf6", "#6d28d9"],
      level: 4,
    },
    {
      title: "CapCut",
      description: "AI-powered cuts, captions, and effects for short-form video.",
      url: "https://www.capcut.com",
      tags: ["Video", "Short-form", "TikTok"],
      icon: "\u{1F4FA}",
      color: ["#ef4444", "#b91c1c"],
      level: 2,
    },
    {
      title: "Adobe Firefly",
      description: "Generate images, vectors, and edits. Ethical, licensed training.",
      url: "https://www.adobe.com/products/firefly.html",
      tags: ["Image", "Design", "Adobe"],
      icon: "\u{1F525}",
      color: ["#ff3366", "#cc2952"],
      level: 2,
    },
    {
      title: "Canva AI",
      description: "Magic Design, background removal, text-to-image for presentations.",
      url: "https://www.canva.com",
      tags: ["Design", "Templates", "Social"],
      icon: "\u{1F3A8}",
      color: ["#00c4cc", "#0099a0"],
      level: 1,
    },
    {
      title: "Luminar Neo",
      description: "AI photo editing: sky replacement, portrait enhancement, one-click fixes.",
      url: "https://skylum.com/luminar",
      tags: ["Photo", "Retouching", "Landscape"],
      icon: "\u{1F4F8}",
      color: ["#0ea5e9", "#0369a1"],
      level: 3,
    },
    {
      title: "EditBot 0",
      description: "AI video editor for media enthusiasts and professionals.",
      url: "https://example.com/editbot 0",
      tags: ["Video", "Content"],
      icon: "📺",
      color: ["#a855f7", "#7e22ce"],
      level: 1,
    },
    {
      title: "MediaAI 1",
      description: "AI content creator for media enthusiasts and professionals.",
      url: "https://example.com/mediaai 1",
      tags: ["Content", "Content"],
      icon: "📺",
      color: ["#ea580c", "#c2410c"],
      level: 1,
    },
    {
      title: "ContentGen 2",
      description: "AI video editor for media enthusiasts and professionals.",
      url: "https://example.com/contentgen 2",
      tags: ["Content", "Media"],
      icon: "📺",
      color: ["#2e7d32", "#1b5e20"],
      level: 3,
    },
    {
      title: "EditBot 3",
      description: "AI media analyzer for media enthusiasts and professionals.",
      url: "https://example.com/editbot 3",
      tags: ["Video", "Content"],
      icon: "📺",
      color: ["#2e7d32", "#1b5e20"],
      level: 1,
    },
    {
      title: "MediaAI 4",
      description: "AI media analyzer for media enthusiasts and professionals.",
      url: "https://example.com/mediaai 4",
      tags: ["Content", "Media"],
      icon: "📺",
      color: ["#ec4899", "#db2777"],
      level: 1,
    },
    {
      title: "ContentGen 5",
      description: "AI video editor for media enthusiasts and professionals.",
      url: "https://example.com/contentgen 5",
      tags: ["Media", "Video"],
      icon: "📺",
      color: ["#2e7d32", "#1b5e20"],
      level: 4,
    },
    {
      title: "EditBot 6",
      description: "AI media analyzer for media enthusiasts and professionals.",
      url: "https://example.com/editbot 6",
      tags: ["Video", "Media"],
      icon: "📺",
      color: ["#ec4899", "#db2777"],
      level: 1,
    },
    {
      title: "ContentGen 7",
      description: "AI media analyzer for media enthusiasts and professionals.",
      url: "https://example.com/contentgen 7",
      tags: ["Media", "Media"],
      icon: "📺",
      color: ["#0d9488", "#0f766e"],
      level: 4,
    },
    {
      title: "ContentGen 8",
      description: "AI content creator for media enthusiasts and professionals.",
      url: "https://example.com/contentgen 8",
      tags: ["Video", "Media"],
      icon: "📺",
      color: ["#0d9488", "#0f766e"],
      level: 4,
    },
    {
      title: "EditBot 9",
      description: "AI video editor for media enthusiasts and professionals.",
      url: "https://example.com/editbot 9",
      tags: ["Media", "Content"],
      icon: "📺",
      color: ["#4285f4", "#34a853"],
      level: 1,
    },
    {
      title: "EditBot 10",
      description: "AI content creator for media enthusiasts and professionals.",
      url: "https://example.com/editbot 10",
      tags: ["Content", "Media"],
      icon: "📺",
      color: ["#1976d2", "#0d47a1"],
      level: 4,
    },
    {
      title: "MediaAI 11",
      description: "AI video editor for media enthusiasts and professionals.",
      url: "https://example.com/mediaai 11",
      tags: ["Video", "Video"],
      icon: "📺",
      color: ["#2e7d32", "#1b5e20"],
      level: 4,
    },
    {
      title: "EditBot 12",
      description: "AI video editor for media enthusiasts and professionals.",
      url: "https://example.com/editbot 12",
      tags: ["Content", "Content"],
      icon: "📺",
      color: ["#0ea5e9", "#0284c7"],
      level: 4,
    },
    {
      title: "ContentGen 13",
      description: "AI media analyzer for media enthusiasts and professionals.",
      url: "https://example.com/contentgen 13",
      tags: ["Media", "Video"],
      icon: "📺",
      color: ["#0ea5e9", "#0284c7"],
      level: 4,
    },
    {
      title: "ContentGen 14",
      description: "AI video editor for media enthusiasts and professionals.",
      url: "https://example.com/contentgen 14",
      tags: ["Content", "Media"],
      icon: "📺",
      color: ["#a855f7", "#7e22ce"],
      level: 4,
    },
    {
      title: "MediaAI 15",
      description: "AI media analyzer for media enthusiasts and professionals.",
      url: "https://example.com/mediaai 15",
      tags: ["Content", "Media"],
      icon: "📺",
      color: ["#ea580c", "#c2410c"],
      level: 2,
    },
    {
      title: "ContentGen 16",
      description: "AI video editor for media enthusiasts and professionals.",
      url: "https://example.com/contentgen 16",
      tags: ["Media", "Media"],
      icon: "📺",
      color: ["#2e7d32", "#1b5e20"],
      level: 4,
    },
    {
      title: "ContentGen 17",
      description: "AI video editor for media enthusiasts and professionals.",
      url: "https://example.com/contentgen 17",
      tags: ["Content", "Media"],
      icon: "📺",
      color: ["#ec4899", "#db2777"],
      level: 3,
    },
    {
      title: "EditBot 18",
      description: "AI media analyzer for media enthusiasts and professionals.",
      url: "https://example.com/editbot 18",
      tags: ["Media", "Media"],
      icon: "📺",
      color: ["#ea580c", "#c2410c"],
      level: 4,
    }

  ],
  entertainment: [
    {
      title: "Suno",
      description: "Create full songs from text prompts. AI music generation.",
      url: "https://suno.com",
      tags: ["Music", "Generation", "Songs"],
      icon: "\u{1F3B5}",
      color: ["#f97316", "#ea580c"],
      level: 1,
    },
    {
      title: "Udio",
      description: "AI music creation. Generate tracks in any style or genre.",
      url: "https://www.udio.com",
      tags: ["Music", "Generation", "Genres"],
      icon: "\u{1F3BA}",
      color: ["#6366f1", "#4f46e5"],
      level: 1,
    },
    {
      title: "ChatGPT Movie Recs",
      description: "Get movie and TV recommendations based on mood and preferences.",
      url: "https://chat.openai.com",
      tags: ["Movies", "TV", "Recommendations"],
      icon: "\u{1F3AC}",
      color: ["#10a37f", "#1a7f5a"],
      level: 1,
    },
    {
      title: "Midjourney",
      description: "Generate art for album covers, posters, and creative projects.",
      url: "https://midjourney.com",
      tags: ["Art", "Generation", "Creative"],
      icon: "\u{1F3A8}",
      color: ["#e44d8a", "#b83280"],
      level: 2,
    },
    {
      title: "Character.AI",
      description: "Chat with AI characters. Roleplay, storytelling, and fun.",
      url: "https://character.ai",
      tags: ["Chat", "Roleplay", "Characters"],
      icon: "\u{1F9DE}",
      color: ["#8b5cf6", "#7c3aed"],
      level: 1,
    },
    {
      title: "Inworld",
      description: "Create AI NPCs for games. Conversational, emotionally intelligent.",
      url: "https://www.inworld.ai",
      tags: ["Gaming", "NPCs", "Conversational"],
      icon: "\u{1F3AE}",
      color: ["#06b6d4", "#0891b2"],
      level: 5,
    },
    {
      title: "EntertainAI 0",
      description: "AI game assistant for entertainment enthusiasts and professionals.",
      url: "https://example.com/entertainai 0",
      tags: ["Entertainment", "Entertainment"],
      icon: "🎭",
      color: ["#ef4444", "#b91c1c"],
      level: 2,
    },
    {
      title: "EntertainAI 1",
      description: "AI music generator for entertainment enthusiasts and professionals.",
      url: "https://example.com/entertainai 1",
      tags: ["Gaming", "Gaming"],
      icon: "🎭",
      color: ["#7c3aed", "#5b21b6"],
      level: 3,
    },
    {
      title: "EntertainAI 2",
      description: "AI game assistant for entertainment enthusiasts and professionals.",
      url: "https://example.com/entertainai 2",
      tags: ["Entertainment", "Entertainment"],
      icon: "🎭",
      color: ["#7c3aed", "#5b21b6"],
      level: 3,
    },
    {
      title: "MusicBot 3",
      description: "AI music generator for entertainment enthusiasts and professionals.",
      url: "https://example.com/musicbot 3",
      tags: ["Entertainment", "Gaming"],
      icon: "🎭",
      color: ["#ef4444", "#b91c1c"],
      level: 2,
    },
    {
      title: "MusicBot 4",
      description: "AI music generator for entertainment enthusiasts and professionals.",
      url: "https://example.com/musicbot 4",
      tags: ["Entertainment", "Music"],
      icon: "🎭",
      color: ["#ea580c", "#c2410c"],
      level: 1,
    },
    {
      title: "MusicBot 5",
      description: "AI game assistant for entertainment enthusiasts and professionals.",
      url: "https://example.com/musicbot 5",
      tags: ["Entertainment", "Gaming"],
      icon: "🎭",
      color: ["#0ea5e9", "#0284c7"],
      level: 4,
    },
    {
      title: "EntertainAI 6",
      description: "AI music generator for entertainment enthusiasts and professionals.",
      url: "https://example.com/entertainai 6",
      tags: ["Entertainment", "Music"],
      icon: "🎭",
      color: ["#1976d2", "#0d47a1"],
      level: 4,
    },
    {
      title: "MusicBot 7",
      description: "AI game assistant for entertainment enthusiasts and professionals.",
      url: "https://example.com/musicbot 7",
      tags: ["Gaming", "Music"],
      icon: "🎭",
      color: ["#0ea5e9", "#0284c7"],
      level: 4,
    },
    {
      title: "GameAssist 8",
      description: "AI game assistant for entertainment enthusiasts and professionals.",
      url: "https://example.com/gameassist 8",
      tags: ["Gaming", "Music"],
      icon: "🎭",
      color: ["#ec4899", "#db2777"],
      level: 4,
    },
    {
      title: "MusicBot 9",
      description: "AI music generator for entertainment enthusiasts and professionals.",
      url: "https://example.com/musicbot 9",
      tags: ["Gaming", "Gaming"],
      icon: "🎭",
      color: ["#0d9488", "#0f766e"],
      level: 1,
    },
    {
      title: "MusicBot 10",
      description: "AI recommendation engine for entertainment enthusiasts and professionals.",
      url: "https://example.com/musicbot 10",
      tags: ["Gaming", "Music"],
      icon: "🎭",
      color: ["#0d9488", "#0f766e"],
      level: 3,
    },
    {
      title: "MusicBot 11",
      description: "AI music generator for entertainment enthusiasts and professionals.",
      url: "https://example.com/musicbot 11",
      tags: ["Entertainment", "Entertainment"],
      icon: "🎭",
      color: ["#ef4444", "#b91c1c"],
      level: 2,
    },
    {
      title: "GameAssist 12",
      description: "AI recommendation engine for entertainment enthusiasts and professionals.",
      url: "https://example.com/gameassist 12",
      tags: ["Music", "Music"],
      icon: "🎭",
      color: ["#ef4444", "#b91c1c"],
      level: 4,
    },
    {
      title: "GameAssist 13",
      description: "AI recommendation engine for entertainment enthusiasts and professionals.",
      url: "https://example.com/gameassist 13",
      tags: ["Gaming", "Gaming"],
      icon: "🎭",
      color: ["#7c3aed", "#5b21b6"],
      level: 4,
    },
    {
      title: "EntertainAI 14",
      description: "AI music generator for entertainment enthusiasts and professionals.",
      url: "https://example.com/entertainai 14",
      tags: ["Entertainment", "Music"],
      icon: "🎭",
      color: ["#ef4444", "#b91c1c"],
      level: 2,
    },
    {
      title: "EntertainAI 15",
      description: "AI recommendation engine for entertainment enthusiasts and professionals.",
      url: "https://example.com/entertainai 15",
      tags: ["Entertainment", "Music"],
      icon: "🎭",
      color: ["#7c3aed", "#5b21b6"],
      level: 4,
    },
    {
      title: "EntertainAI 16",
      description: "AI music generator for entertainment enthusiasts and professionals.",
      url: "https://example.com/entertainai 16",
      tags: ["Gaming", "Gaming"],
      icon: "🎭",
      color: ["#059669", "#047857"],
      level: 2,
    },
    {
      title: "EntertainAI 17",
      description: "AI music generator for entertainment enthusiasts and professionals.",
      url: "https://example.com/entertainai 17",
      tags: ["Entertainment", "Gaming"],
      icon: "🎭",
      color: ["#0ea5e9", "#0284c7"],
      level: 2,
    },
    {
      title: "GameAssist 18",
      description: "AI recommendation engine for entertainment enthusiasts and professionals.",
      url: "https://example.com/gameassist 18",
      tags: ["Entertainment", "Music"],
      icon: "🎭",
      color: ["#0ea5e9", "#0284c7"],
      level: 3,
    }

  ],
  sports: [
    {
      title: "ChatGPT Sports Analysis",
      description: "Get stats, predictions, and breakdowns. Fantasy and betting insights.",
      url: "https://chat.openai.com",
      tags: ["Analysis", "Stats", "Fantasy"],
      icon: "\u{26BD}",
      color: ["#10a37f", "#1a7f5a"],
      level: 1,
    },
    {
      title: "ESPN Fantasy",
      description: "AI-powered projections, lineup optimizers, and waiver suggestions.",
      url: "https://fantasy.espn.com",
      tags: ["Fantasy", "Football", "Basketball"],
      icon: "\u{1F3C8}",
      color: ["#dc2626", "#b91c1c"],
      level: 2,
    },
    {
      title: "Sportradar",
      description: "AI analytics for live betting, player tracking, and performance.",
      url: "https://sportradar.com",
      tags: ["Analytics", "Betting", "Data"],
      icon: "\u{1F4CA}",
      color: ["#0d9488", "#0f766e"],
      level: 6,
    },
    {
      title: "Whoop",
      description: "AI recovery and strain analysis. Optimize training and sleep.",
      url: "https://www.whoop.com",
      tags: ["Fitness", "Recovery", "Wearable"],
      icon: "\u{1F3CB}\u{FE0F}",
      color: ["#000000", "#374151"],
      level: 2,
    },
    {
      title: "HomeCourt",
      description: "AI basketball trainer. Tracks shots, drills, and improvement over time.",
      url: "https://www.homecourt.ai",
      tags: ["Basketball", "Training", "Tracking"],
      icon: "\u{1F3C0}",
      color: ["#f59e0b", "#d97706"],
      level: 2,
    },
    {
      title: "Zwift",
      description: "AI-paced cycling and running. Virtual worlds and structured workouts.",
      url: "https://www.zwift.com",
      tags: ["Cycling", "Running", "Indoor"],
      icon: "\u{1F3C4}",
      color: ["#22c55e", "#16a34a"],
      level: 2,
    },
    {
      title: "SportsAI 0",
      description: "AI training planner for sports enthusiasts and professionals.",
      url: "https://example.com/sportsai 0",
      tags: ["Sports", "Sports"],
      icon: "⚽",
      color: ["#ea580c", "#c2410c"],
      level: 3,
    },
    {
      title: "StatsBot 1",
      description: "AI training planner for sports enthusiasts and professionals.",
      url: "https://example.com/statsbot 1",
      tags: ["Sports", "Stats"],
      icon: "⚽",
      color: ["#ec4899", "#db2777"],
      level: 2,
    },
    {
      title: "TrainingAssist 2",
      description: "AI stats analyzer for sports enthusiasts and professionals.",
      url: "https://example.com/trainingassist 2",
      tags: ["Sports", "Sports"],
      icon: "⚽",
      color: ["#0ea5e9", "#0284c7"],
      level: 4,
    },
    {
      title: "StatsBot 3",
      description: "AI training planner for sports enthusiasts and professionals.",
      url: "https://example.com/statsbot 3",
      tags: ["Stats", "Stats"],
      icon: "⚽",
      color: ["#059669", "#047857"],
      level: 3,
    },
    {
      title: "TrainingAssist 4",
      description: "AI training planner for sports enthusiasts and professionals.",
      url: "https://example.com/trainingassist 4",
      tags: ["Sports", "Sports"],
      icon: "⚽",
      color: ["#ec4899", "#db2777"],
      level: 4,
    },
    {
      title: "StatsBot 5",
      description: "AI stats analyzer for sports enthusiasts and professionals.",
      url: "https://example.com/statsbot 5",
      tags: ["Sports", "Stats"],
      icon: "⚽",
      color: ["#2e7d32", "#1b5e20"],
      level: 2,
    },
    {
      title: "TrainingAssist 6",
      description: "AI training planner for sports enthusiasts and professionals.",
      url: "https://example.com/trainingassist 6",
      tags: ["Sports", "Sports"],
      icon: "⚽",
      color: ["#4285f4", "#34a853"],
      level: 2,
    },
    {
      title: "SportsAI 7",
      description: "AI stats analyzer for sports enthusiasts and professionals.",
      url: "https://example.com/sportsai 7",
      tags: ["Fitness", "Sports"],
      icon: "⚽",
      color: ["#0ea5e9", "#0284c7"],
      level: 1,
    },
    {
      title: "StatsBot 8",
      description: "AI training planner for sports enthusiasts and professionals.",
      url: "https://example.com/statsbot 8",
      tags: ["Sports", "Sports"],
      icon: "⚽",
      color: ["#00a8e1", "#0077b6"],
      level: 1,
    },
    {
      title: "StatsBot 9",
      description: "AI fantasy helper for sports enthusiasts and professionals.",
      url: "https://example.com/statsbot 9",
      tags: ["Sports", "Stats"],
      icon: "⚽",
      color: ["#00a8e1", "#0077b6"],
      level: 3,
    },
    {
      title: "TrainingAssist 10",
      description: "AI stats analyzer for sports enthusiasts and professionals.",
      url: "https://example.com/trainingassist 10",
      tags: ["Sports", "Fitness"],
      icon: "⚽",
      color: ["#059669", "#047857"],
      level: 4,
    },
    {
      title: "StatsBot 11",
      description: "AI stats analyzer for sports enthusiasts and professionals.",
      url: "https://example.com/statsbot 11",
      tags: ["Sports", "Fitness"],
      icon: "⚽",
      color: ["#1976d2", "#0d47a1"],
      level: 2,
    },
    {
      title: "TrainingAssist 12",
      description: "AI training planner for sports enthusiasts and professionals.",
      url: "https://example.com/trainingassist 12",
      tags: ["Fitness", "Fitness"],
      icon: "⚽",
      color: ["#00a8e1", "#0077b6"],
      level: 2,
    },
    {
      title: "TrainingAssist 13",
      description: "AI training planner for sports enthusiasts and professionals.",
      url: "https://example.com/trainingassist 13",
      tags: ["Fitness", "Stats"],
      icon: "⚽",
      color: ["#00a8e1", "#0077b6"],
      level: 1,
    },
    {
      title: "StatsBot 14",
      description: "AI stats analyzer for sports enthusiasts and professionals.",
      url: "https://example.com/statsbot 14",
      tags: ["Sports", "Stats"],
      icon: "⚽",
      color: ["#059669", "#047857"],
      level: 2,
    },
    {
      title: "SportsAI 15",
      description: "AI stats analyzer for sports enthusiasts and professionals.",
      url: "https://example.com/sportsai 15",
      tags: ["Sports", "Stats"],
      icon: "⚽",
      color: ["#4285f4", "#34a853"],
      level: 4,
    },
    {
      title: "StatsBot 16",
      description: "AI fantasy helper for sports enthusiasts and professionals.",
      url: "https://example.com/statsbot 16",
      tags: ["Stats", "Sports"],
      icon: "⚽",
      color: ["#059669", "#047857"],
      level: 2,
    },
    {
      title: "StatsBot 17",
      description: "AI stats analyzer for sports enthusiasts and professionals.",
      url: "https://example.com/statsbot 17",
      tags: ["Sports", "Stats"],
      icon: "⚽",
      color: ["#0d9488", "#0f766e"],
      level: 1,
    },
    {
      title: "TrainingAssist 18",
      description: "AI fantasy helper for sports enthusiasts and professionals.",
      url: "https://example.com/trainingassist 18",
      tags: ["Sports", "Fitness"],
      icon: "⚽",
      color: ["#2e7d32", "#1b5e20"],
      level: 1,
    }

  ],
  health: [
    {
      title: "HealthCoach 0",
      description: "AI mental health support for health enthusiasts and professionals.",
      url: "https://example.com/healthcoach 0",
      tags: ["Health", "Wellness"],
      icon: "🧺",
      color: ["#4285f4", "#34a853"],
      level: 1,
    },
    {
      title: "MediScan 1",
      description: "AI wellness assistant for health enthusiasts and professionals.",
      url: "https://example.com/mediscan 1",
      tags: ["Wellness", "Health"],
      icon: "🧺",
      color: ["#0d9488", "#0f766e"],
      level: 1,
    },
    {
      title: "HealthAI 2",
      description: "AI wellness assistant for health enthusiasts and professionals.",
      url: "https://example.com/healthai 2",
      tags: ["Health", "Medical"],
      icon: "🧺",
      color: ["#1976d2", "#0d47a1"],
      level: 3,
    },
    {
      title: "MediScan 3",
      description: "AI symptom checker for health enthusiasts and professionals.",
      url: "https://example.com/mediscan 3",
      tags: ["Fitness", "Mental Health"],
      icon: "🧺",
      color: ["#7c3aed", "#5b21b6"],
      level: 2,
    },
    {
      title: "HealthAI 4",
      description: "AI medical Q&A for health enthusiasts and professionals.",
      url: "https://example.com/healthai 4",
      tags: ["Fitness", "Fitness"],
      icon: "🧺",
      color: ["#7c3aed", "#5b21b6"],
      level: 3,
    },
    {
      title: "WellnessAI 5",
      description: "AI fitness tracker for health enthusiasts and professionals.",
      url: "https://example.com/wellnessai 5",
      tags: ["Medical", "Medical"],
      icon: "🧺",
      color: ["#059669", "#047857"],
      level: 3,
    },
    {
      title: "HealthAI 6",
      description: "AI medical Q&A for health enthusiasts and professionals.",
      url: "https://example.com/healthai 6",
      tags: ["Fitness", "Fitness"],
      icon: "🧺",
      color: ["#ec4899", "#db2777"],
      level: 4,
    },
    {
      title: "VitalTrack 7",
      description: "AI medical Q&A for health enthusiasts and professionals.",
      url: "https://example.com/vitaltrack 7",
      tags: ["Medical", "Wellness"],
      icon: "🧺",
      color: ["#059669", "#047857"],
      level: 1,
    },
    {
      title: "CareAssist 8",
      description: "AI fitness tracker for health enthusiasts and professionals.",
      url: "https://example.com/careassist 8",
      tags: ["Mental Health", "Wellness"],
      icon: "🧺",
      color: ["#4285f4", "#34a853"],
      level: 3,
    },
    {
      title: "WellnessAI 9",
      description: "AI symptom checker for health enthusiasts and professionals.",
      url: "https://example.com/wellnessai 9",
      tags: ["Medical", "Fitness"],
      icon: "🧺",
      color: ["#ec4899", "#db2777"],
      level: 1,
    },
    {
      title: "HealthCoach 10",
      description: "AI fitness tracker for health enthusiasts and professionals.",
      url: "https://example.com/healthcoach 10",
      tags: ["Fitness", "Medical"],
      icon: "🧺",
      color: ["#0ea5e9", "#0284c7"],
      level: 4,
    },
    {
      title: "WellnessAI 11",
      description: "AI symptom checker for health enthusiasts and professionals.",
      url: "https://example.com/wellnessai 11",
      tags: ["Medical", "Mental Health"],
      icon: "🧺",
      color: ["#059669", "#047857"],
      level: 1,
    },
    {
      title: "MediScan 12",
      description: "AI mental health support for health enthusiasts and professionals.",
      url: "https://example.com/mediscan 12",
      tags: ["Fitness", "Wellness"],
      icon: "🧺",
      color: ["#0ea5e9", "#0284c7"],
      level: 1,
    },
    {
      title: "HealthAI 13",
      description: "AI symptom checker for health enthusiasts and professionals.",
      url: "https://example.com/healthai 13",
      tags: ["Health", "Health"],
      icon: "🧺",
      color: ["#ec4899", "#db2777"],
      level: 3,
    },
    {
      title: "VitalTrack 14",
      description: "AI symptom checker for health enthusiasts and professionals.",
      url: "https://example.com/vitaltrack 14",
      tags: ["Mental Health", "Wellness"],
      icon: "🧺",
      color: ["#4285f4", "#34a853"],
      level: 1,
    },
    {
      title: "HealthCoach 15",
      description: "AI medical Q&A for health enthusiasts and professionals.",
      url: "https://example.com/healthcoach 15",
      tags: ["Health", "Health"],
      icon: "🧺",
      color: ["#ef4444", "#b91c1c"],
      level: 1,
    },
    {
      title: "HealthAI 16",
      description: "AI wellness assistant for health enthusiasts and professionals.",
      url: "https://example.com/healthai 16",
      tags: ["Fitness", "Medical"],
      icon: "🧺",
      color: ["#059669", "#047857"],
      level: 2,
    },
    {
      title: "CareAssist 17",
      description: "AI fitness tracker for health enthusiasts and professionals.",
      url: "https://example.com/careassist 17",
      tags: ["Health", "Fitness"],
      icon: "🧺",
      color: ["#0d9488", "#0f766e"],
      level: 4,
    },
    {
      title: "SymptomBot 18",
      description: "AI fitness tracker for health enthusiasts and professionals.",
      url: "https://example.com/symptombot 18",
      tags: ["Medical", "Fitness"],
      icon: "🧺",
      color: ["#a855f7", "#7e22ce"],
      level: 1,
    }
  ],
  education: [
    {
      title: "SkillForge 0",
      description: "AI course recommender for education enthusiasts and professionals.",
      url: "https://example.com/skillforge 0",
      tags: ["Study", "Tutoring"],
      icon: "🎒",
      color: ["#00a8e1", "#0077b6"],
      level: 3,
    },
    {
      title: "LearnAI 1",
      description: "AI course recommender for education enthusiasts and professionals.",
      url: "https://example.com/learnai 1",
      tags: ["Study", "Learning"],
      icon: "🎒",
      color: ["#2e7d32", "#1b5e20"],
      level: 1,
    },
    {
      title: "TutorPro 2",
      description: "AI flashcard maker for education enthusiasts and professionals.",
      url: "https://example.com/tutorpro 2",
      tags: ["Tutoring", "Education"],
      icon: "🎒",
      color: ["#ef4444", "#b91c1c"],
      level: 4,
    },
    {
      title: "StudyBuddy 3",
      description: "AI flashcard maker for education enthusiasts and professionals.",
      url: "https://example.com/studybuddy 3",
      tags: ["Education", "Learning"],
      icon: "🎒",
      color: ["#ef4444", "#b91c1c"],
      level: 3,
    },
    {
      title: "CourseAssist 4",
      description: "AI flashcard maker for education enthusiasts and professionals.",
      url: "https://example.com/courseassist 4",
      tags: ["Study", "Tutoring"],
      icon: "🎒",
      color: ["#ec4899", "#db2777"],
      level: 1,
    },
    {
      title: "TutorPro 5",
      description: "AI flashcard maker for education enthusiasts and professionals.",
      url: "https://example.com/tutorpro 5",
      tags: ["Tutoring", "Education"],
      icon: "🎒",
      color: ["#1976d2", "#0d47a1"],
      level: 3,
    },
    {
      title: "CourseAssist 6",
      description: "AI tutoring assistant for education enthusiasts and professionals.",
      url: "https://example.com/courseassist 6",
      tags: ["Tutoring", "Tutoring"],
      icon: "🎒",
      color: ["#1976d2", "#0d47a1"],
      level: 4,
    },
    {
      title: "LearnAI 7",
      description: "AI study planner for education enthusiasts and professionals.",
      url: "https://example.com/learnai 7",
      tags: ["Study", "Learning"],
      icon: "🎒",
      color: ["#0ea5e9", "#0284c7"],
      level: 4,
    },
    {
      title: "CourseAssist 8",
      description: "AI quiz generator for education enthusiasts and professionals.",
      url: "https://example.com/courseassist 8",
      tags: ["Education", "Courses"],
      icon: "🎒",
      color: ["#2e7d32", "#1b5e20"],
      level: 2,
    },
    {
      title: "StudyBuddy 9",
      description: "AI quiz generator for education enthusiasts and professionals.",
      url: "https://example.com/studybuddy 9",
      tags: ["Education", "Courses"],
      icon: "🎒",
      color: ["#ea580c", "#c2410c"],
      level: 4,
    },
    {
      title: "SkillForge 10",
      description: "AI study planner for education enthusiasts and professionals.",
      url: "https://example.com/skillforge 10",
      tags: ["Tutoring", "Education"],
      icon: "🎒",
      color: ["#2e7d32", "#1b5e20"],
      level: 4,
    },
    {
      title: "EduBot 11",
      description: "AI tutoring assistant for education enthusiasts and professionals.",
      url: "https://example.com/edubot 11",
      tags: ["Learning", "Courses"],
      icon: "🎒",
      color: ["#4285f4", "#34a853"],
      level: 3,
    },
    {
      title: "StudyBuddy 12",
      description: "AI tutoring assistant for education enthusiasts and professionals.",
      url: "https://example.com/studybuddy 12",
      tags: ["Education", "Courses"],
      icon: "🎒",
      color: ["#a855f7", "#7e22ce"],
      level: 4,
    },
    {
      title: "SkillForge 13",
      description: "AI tutoring assistant for education enthusiasts and professionals.",
      url: "https://example.com/skillforge 13",
      tags: ["Courses", "Study"],
      icon: "🎒",
      color: ["#0d9488", "#0f766e"],
      level: 2,
    },
    {
      title: "StudyBuddy 14",
      description: "AI tutoring assistant for education enthusiasts and professionals.",
      url: "https://example.com/studybuddy 14",
      tags: ["Tutoring", "Study"],
      icon: "🎒",
      color: ["#a855f7", "#7e22ce"],
      level: 1,
    },
    {
      title: "EduBot 15",
      description: "AI quiz generator for education enthusiasts and professionals.",
      url: "https://example.com/edubot 15",
      tags: ["Courses", "Tutoring"],
      icon: "🎒",
      color: ["#0ea5e9", "#0284c7"],
      level: 1,
    },
    {
      title: "EduBot 16",
      description: "AI quiz generator for education enthusiasts and professionals.",
      url: "https://example.com/edubot 16",
      tags: ["Study", "Tutoring"],
      icon: "🎒",
      color: ["#a855f7", "#7e22ce"],
      level: 1,
    },
    {
      title: "EduBot 17",
      description: "AI flashcard maker for education enthusiasts and professionals.",
      url: "https://example.com/edubot 17",
      tags: ["Learning", "Study"],
      icon: "🎒",
      color: ["#059669", "#047857"],
      level: 2,
    },
    {
      title: "TutorPro 18",
      description: "AI study planner for education enthusiasts and professionals.",
      url: "https://example.com/tutorpro 18",
      tags: ["Courses", "Study"],
      icon: "🎒",
      color: ["#7c3aed", "#5b21b6"],
      level: 3,
    }
  ],
  finance: [
    {
      title: "BudgetAI 0",
      description: "AI budget planner for finance enthusiasts and professionals.",
      url: "https://example.com/budgetai 0",
      tags: ["Crypto", "Savings"],
      icon: "💰",
      color: ["#0ea5e9", "#0284c7"],
      level: 4,
    },
    {
      title: "BudgetAI 1",
      description: "AI budget planner for finance enthusiasts and professionals.",
      url: "https://example.com/budgetai 1",
      tags: ["Budget", "Investing"],
      icon: "💰",
      color: ["#ef4444", "#b91c1c"],
      level: 3,
    },
    {
      title: "MoneyMind 2",
      description: "AI budget planner for finance enthusiasts and professionals.",
      url: "https://example.com/moneymind 2",
      tags: ["Savings", "Budget"],
      icon: "💰",
      color: ["#059669", "#047857"],
      level: 2,
    },
    {
      title: "WealthTrack 3",
      description: "AI savings optimizer for finance enthusiasts and professionals.",
      url: "https://example.com/wealthtrack 3",
      tags: ["Crypto", "Crypto"],
      icon: "💰",
      color: ["#ea580c", "#c2410c"],
      level: 4,
    },
    {
      title: "MoneyMind 4",
      description: "AI portfolio analyzer for finance enthusiasts and professionals.",
      url: "https://example.com/moneymind 4",
      tags: ["Crypto", "Budget"],
      icon: "💰",
      color: ["#059669", "#047857"],
      level: 4,
    },
    {
      title: "BudgetAI 5",
      description: "AI investment advisor for finance enthusiasts and professionals.",
      url: "https://example.com/budgetai 5",
      tags: ["Finance", "Budget"],
      icon: "💰",
      color: ["#ec4899", "#db2777"],
      level: 3,
    },
    {
      title: "SaveSmart 6",
      description: "AI budget planner for finance enthusiasts and professionals.",
      url: "https://example.com/savesmart 6",
      tags: ["Savings", "Budget"],
      icon: "💰",
      color: ["#ec4899", "#db2777"],
      level: 1,
    },
    {
      title: "SaveSmart 7",
      description: "AI expense tracker for finance enthusiasts and professionals.",
      url: "https://example.com/savesmart 7",
      tags: ["Finance", "Finance"],
      icon: "💰",
      color: ["#ef4444", "#b91c1c"],
      level: 2,
    },
    {
      title: "SaveSmart 8",
      description: "AI investment advisor for finance enthusiasts and professionals.",
      url: "https://example.com/savesmart 8",
      tags: ["Investing", "Crypto"],
      icon: "💰",
      color: ["#7c3aed", "#5b21b6"],
      level: 4,
    },
    {
      title: "BudgetAI 9",
      description: "AI savings optimizer for finance enthusiasts and professionals.",
      url: "https://example.com/budgetai 9",
      tags: ["Budget", "Investing"],
      icon: "💰",
      color: ["#4285f4", "#34a853"],
      level: 3,
    },
    {
      title: "SaveSmart 10",
      description: "AI expense tracker for finance enthusiasts and professionals.",
      url: "https://example.com/savesmart 10",
      tags: ["Savings", "Budget"],
      icon: "💰",
      color: ["#1976d2", "#0d47a1"],
      level: 3,
    },
    {
      title: "CryptoAI 11",
      description: "AI savings optimizer for finance enthusiasts and professionals.",
      url: "https://example.com/cryptoai 11",
      tags: ["Savings", "Budget"],
      icon: "💰",
      color: ["#2e7d32", "#1b5e20"],
      level: 4,
    },
    {
      title: "WealthTrack 12",
      description: "AI portfolio analyzer for finance enthusiasts and professionals.",
      url: "https://example.com/wealthtrack 12",
      tags: ["Finance", "Budget"],
      icon: "💰",
      color: ["#0d9488", "#0f766e"],
      level: 3,
    },
    {
      title: "CryptoAI 13",
      description: "AI budget planner for finance enthusiasts and professionals.",
      url: "https://example.com/cryptoai 13",
      tags: ["Investing", "Crypto"],
      icon: "💰",
      color: ["#0d9488", "#0f766e"],
      level: 4,
    },
    {
      title: "CryptoAI 14",
      description: "AI budget planner for finance enthusiasts and professionals.",
      url: "https://example.com/cryptoai 14",
      tags: ["Investing", "Budget"],
      icon: "💰",
      color: ["#0ea5e9", "#0284c7"],
      level: 2,
    },
    {
      title: "MoneyMind 15",
      description: "AI investment advisor for finance enthusiasts and professionals.",
      url: "https://example.com/moneymind 15",
      tags: ["Investing", "Savings"],
      icon: "💰",
      color: ["#a855f7", "#7e22ce"],
      level: 4,
    },
    {
      title: "BudgetAI 16",
      description: "AI savings optimizer for finance enthusiasts and professionals.",
      url: "https://example.com/budgetai 16",
      tags: ["Savings", "Finance"],
      icon: "💰",
      color: ["#2e7d32", "#1b5e20"],
      level: 2,
    },
    {
      title: "MoneyMind 17",
      description: "AI savings optimizer for finance enthusiasts and professionals.",
      url: "https://example.com/moneymind 17",
      tags: ["Budget", "Finance"],
      icon: "💰",
      color: ["#1976d2", "#0d47a1"],
      level: 4,
    },
    {
      title: "FinanceGenie 18",
      description: "AI investment advisor for finance enthusiasts and professionals.",
      url: "https://example.com/financegenie 18",
      tags: ["Crypto", "Savings"],
      icon: "💰",
      color: ["#0ea5e9", "#0284c7"],
      level: 1,
    }
  ],
  legal: [
    {
      title: "ClaimHelper 0",
      description: "AI document analyzer for legal enthusiasts and professionals.",
      url: "https://example.com/claimhelper 0",
      tags: ["Contracts", "Documents"],
      icon: "⚖️",
      color: ["#a855f7", "#7e22ce"],
      level: 1,
    },
    {
      title: "ClaimHelper 1",
      description: "AI legal Q&A for legal enthusiasts and professionals.",
      url: "https://example.com/claimhelper 1",
      tags: ["Contracts", "Compliance"],
      icon: "⚖️",
      color: ["#1976d2", "#0d47a1"],
      level: 3,
    },
    {
      title: "LegalAI 2",
      description: "AI legal Q&A for legal enthusiasts and professionals.",
      url: "https://example.com/legalai 2",
      tags: ["Legal", "Legal"],
      icon: "⚖️",
      color: ["#0ea5e9", "#0284c7"],
      level: 2,
    },
    {
      title: "NotaryAI 3",
      description: "AI compliance checker for legal enthusiasts and professionals.",
      url: "https://example.com/notaryai 3",
      tags: ["Contracts", "Contracts"],
      icon: "⚖️",
      color: ["#2e7d32", "#1b5e20"],
      level: 4,
    },
    {
      title: "ComplianceAI 4",
      description: "AI claim assistant for legal enthusiasts and professionals.",
      url: "https://example.com/complianceai 4",
      tags: ["Compliance", "Documents"],
      icon: "⚖️",
      color: ["#ea580c", "#c2410c"],
      level: 4,
    },
    {
      title: "ContractBot 5",
      description: "AI claim assistant for legal enthusiasts and professionals.",
      url: "https://example.com/contractbot 5",
      tags: ["Compliance", "Compliance"],
      icon: "⚖️",
      color: ["#4285f4", "#34a853"],
      level: 3,
    },
    {
      title: "LawAssist 6",
      description: "AI compliance checker for legal enthusiasts and professionals.",
      url: "https://example.com/lawassist 6",
      tags: ["Legal", "Compliance"],
      icon: "⚖️",
      color: ["#a855f7", "#7e22ce"],
      level: 2,
    },
    {
      title: "ContractBot 7",
      description: "AI contract reviewer for legal enthusiasts and professionals.",
      url: "https://example.com/contractbot 7",
      tags: ["Compliance", "Compliance"],
      icon: "⚖️",
      color: ["#059669", "#047857"],
      level: 1,
    },
    {
      title: "LegalAI 8",
      description: "AI contract reviewer for legal enthusiasts and professionals.",
      url: "https://example.com/legalai 8",
      tags: ["Compliance", "Compliance"],
      icon: "⚖️",
      color: ["#2e7d32", "#1b5e20"],
      level: 1,
    },
    {
      title: "NotaryAI 9",
      description: "AI contract reviewer for legal enthusiasts and professionals.",
      url: "https://example.com/notaryai 9",
      tags: ["Compliance", "Compliance"],
      icon: "⚖️",
      color: ["#0ea5e9", "#0284c7"],
      level: 3,
    },
    {
      title: "ClaimHelper 10",
      description: "AI document analyzer for legal enthusiasts and professionals.",
      url: "https://example.com/claimhelper 10",
      tags: ["Documents", "Contracts"],
      icon: "⚖️",
      color: ["#2e7d32", "#1b5e20"],
      level: 2,
    },
    {
      title: "LegalAI 11",
      description: "AI legal Q&A for legal enthusiasts and professionals.",
      url: "https://example.com/legalai 11",
      tags: ["Contracts", "Documents"],
      icon: "⚖️",
      color: ["#0ea5e9", "#0284c7"],
      level: 3,
    },
    {
      title: "DocReview 12",
      description: "AI compliance checker for legal enthusiasts and professionals.",
      url: "https://example.com/docreview 12",
      tags: ["Compliance", "Compliance"],
      icon: "⚖️",
      color: ["#4285f4", "#34a853"],
      level: 2,
    },
    {
      title: "ClaimHelper 13",
      description: "AI compliance checker for legal enthusiasts and professionals.",
      url: "https://example.com/claimhelper 13",
      tags: ["Documents", "Compliance"],
      icon: "⚖️",
      color: ["#4285f4", "#34a853"],
      level: 3,
    },
    {
      title: "DocReview 14",
      description: "AI contract reviewer for legal enthusiasts and professionals.",
      url: "https://example.com/docreview 14",
      tags: ["Contracts", "Documents"],
      icon: "⚖️",
      color: ["#00a8e1", "#0077b6"],
      level: 4,
    },
    {
      title: "ComplianceAI 15",
      description: "AI document analyzer for legal enthusiasts and professionals.",
      url: "https://example.com/complianceai 15",
      tags: ["Contracts", "Legal"],
      icon: "⚖️",
      color: ["#059669", "#047857"],
      level: 3,
    },
    {
      title: "DocReview 16",
      description: "AI contract reviewer for legal enthusiasts and professionals.",
      url: "https://example.com/docreview 16",
      tags: ["Compliance", "Contracts"],
      icon: "⚖️",
      color: ["#059669", "#047857"],
      level: 2,
    },
    {
      title: "ClaimHelper 17",
      description: "AI legal Q&A for legal enthusiasts and professionals.",
      url: "https://example.com/claimhelper 17",
      tags: ["Compliance", "Legal"],
      icon: "⚖️",
      color: ["#0ea5e9", "#0284c7"],
      level: 1,
    },
    {
      title: "ComplianceAI 18",
      description: "AI compliance checker for legal enthusiasts and professionals.",
      url: "https://example.com/complianceai 18",
      tags: ["Compliance", "Legal"],
      icon: "⚖️",
      color: ["#ec4899", "#db2777"],
      level: 1,
    }
  ],
  pets: [
    {
      title: "PetTrainer 0",
      description: "AI nutrition planner for pets enthusiasts and professionals.",
      url: "https://example.com/pettrainer 0",
      tags: ["Pets", "Pets"],
      icon: "🐶",
      color: ["#0ea5e9", "#0284c7"],
      level: 2,
    },
    {
      title: "BreedMatch 1",
      description: "AI training assistant for pets enthusiasts and professionals.",
      url: "https://example.com/breedmatch 1",
      tags: ["Veterinary", "Pets"],
      icon: "🐶",
      color: ["#ef4444", "#b91c1c"],
      level: 4,
    },
    {
      title: "PawAssist 2",
      description: "AI veterinary Q&A for pets enthusiasts and professionals.",
      url: "https://example.com/pawassist 2",
      tags: ["Training", "Training"],
      icon: "🐶",
      color: ["#7c3aed", "#5b21b6"],
      level: 3,
    },
    {
      title: "BreedMatch 3",
      description: "AI veterinary Q&A for pets enthusiasts and professionals.",
      url: "https://example.com/breedmatch 3",
      tags: ["Training", "Pets"],
      icon: "🐶",
      color: ["#7c3aed", "#5b21b6"],
      level: 4,
    },
    {
      title: "AnimalHealth 4",
      description: "AI breed matcher for pets enthusiasts and professionals.",
      url: "https://example.com/animalhealth 4",
      tags: ["Pets", "Pets"],
      icon: "🐶",
      color: ["#ea580c", "#c2410c"],
      level: 3,
    },
    {
      title: "PawAssist 5",
      description: "AI veterinary Q&A for pets enthusiasts and professionals.",
      url: "https://example.com/pawassist 5",
      tags: ["Veterinary", "Training"],
      icon: "🐶",
      color: ["#ef4444", "#b91c1c"],
      level: 4,
    },
    {
      title: "PetTrainer 6",
      description: "AI veterinary Q&A for pets enthusiasts and professionals.",
      url: "https://example.com/pettrainer 6",
      tags: ["Pets", "Care"],
      icon: "🐶",
      color: ["#4285f4", "#34a853"],
      level: 4,
    },
    {
      title: "AnimalHealth 7",
      description: "AI pet care advisor for pets enthusiasts and professionals.",
      url: "https://example.com/animalhealth 7",
      tags: ["Veterinary", "Training"],
      icon: "🐶",
      color: ["#059669", "#047857"],
      level: 2,
    },
    {
      title: "BreedMatch 8",
      description: "AI veterinary Q&A for pets enthusiasts and professionals.",
      url: "https://example.com/breedmatch 8",
      tags: ["Veterinary", "Pets"],
      icon: "🐶",
      color: ["#059669", "#047857"],
      level: 1,
    },
    {
      title: "PetCareAI 9",
      description: "AI nutrition planner for pets enthusiasts and professionals.",
      url: "https://example.com/petcareai 9",
      tags: ["Veterinary", "Pets"],
      icon: "🐶",
      color: ["#ec4899", "#db2777"],
      level: 2,
    },
    {
      title: "PetTrainer 10",
      description: "AI nutrition planner for pets enthusiasts and professionals.",
      url: "https://example.com/pettrainer 10",
      tags: ["Training", "Training"],
      icon: "🐶",
      color: ["#a855f7", "#7e22ce"],
      level: 1,
    },
    {
      title: "PawAssist 11",
      description: "AI breed matcher for pets enthusiasts and professionals.",
      url: "https://example.com/pawassist 11",
      tags: ["Pets", "Care"],
      icon: "🐶",
      color: ["#a855f7", "#7e22ce"],
      level: 4,
    },
    {
      title: "PetTrainer 12",
      description: "AI veterinary Q&A for pets enthusiasts and professionals.",
      url: "https://example.com/pettrainer 12",
      tags: ["Pets", "Care"],
      icon: "🐶",
      color: ["#1976d2", "#0d47a1"],
      level: 3,
    },
    {
      title: "PetCareAI 13",
      description: "AI pet care advisor for pets enthusiasts and professionals.",
      url: "https://example.com/petcareai 13",
      tags: ["Veterinary", "Veterinary"],
      icon: "🐶",
      color: ["#a855f7", "#7e22ce"],
      level: 3,
    },
    {
      title: "PetFoodAI 14",
      description: "AI nutrition planner for pets enthusiasts and professionals.",
      url: "https://example.com/petfoodai 14",
      tags: ["Training", "Veterinary"],
      icon: "🐶",
      color: ["#4285f4", "#34a853"],
      level: 1,
    },
    {
      title: "BreedMatch 15",
      description: "AI veterinary Q&A for pets enthusiasts and professionals.",
      url: "https://example.com/breedmatch 15",
      tags: ["Care", "Care"],
      icon: "🐶",
      color: ["#ec4899", "#db2777"],
      level: 1,
    },
    {
      title: "AnimalHealth 16",
      description: "AI veterinary Q&A for pets enthusiasts and professionals.",
      url: "https://example.com/animalhealth 16",
      tags: ["Pets", "Veterinary"],
      icon: "🐶",
      color: ["#4285f4", "#34a853"],
      level: 3,
    },
    {
      title: "PetFoodAI 17",
      description: "AI training assistant for pets enthusiasts and professionals.",
      url: "https://example.com/petfoodai 17",
      tags: ["Pets", "Training"],
      icon: "🐶",
      color: ["#ec4899", "#db2777"],
      level: 3,
    },
    {
      title: "AnimalHealth 18",
      description: "AI breed matcher for pets enthusiasts and professionals.",
      url: "https://example.com/animalhealth 18",
      tags: ["Training", "Veterinary"],
      icon: "🐶",
      color: ["#ef4444", "#b91c1c"],
      level: 1,
    }
  ],
  food: [
    {
      title: "FoodAllergy 0",
      description: "AI meal planner for food enthusiasts and professionals.",
      url: "https://example.com/foodallergy 0",
      tags: ["Food", "Food"],
      icon: "🍲",
      color: ["#0d9488", "#0f766e"],
      level: 2,
    },
    {
      title: "MealPrep 1",
      description: "AI diet advisor for food enthusiasts and professionals.",
      url: "https://example.com/mealprep 1",
      tags: ["Cooking", "Nutrition"],
      icon: "🍲",
      color: ["#7c3aed", "#5b21b6"],
      level: 4,
    },
    {
      title: "NutritionScan 2",
      description: "AI diet advisor for food enthusiasts and professionals.",
      url: "https://example.com/nutritionscan 2",
      tags: ["Nutrition", "Nutrition"],
      icon: "🍲",
      color: ["#ea580c", "#c2410c"],
      level: 1,
    },
    {
      title: "MealPrep 3",
      description: "AI shopping list maker for food enthusiasts and professionals.",
      url: "https://example.com/mealprep 3",
      tags: ["Cooking", "Diet"],
      icon: "🍲",
      color: ["#00a8e1", "#0077b6"],
      level: 1,
    },
    {
      title: "FoodAllergy 4",
      description: "AI nutrition analyzer for food enthusiasts and professionals.",
      url: "https://example.com/foodallergy 4",
      tags: ["Recipes", "Nutrition"],
      icon: "🍲",
      color: ["#0ea5e9", "#0284c7"],
      level: 4,
    },
    {
      title: "FoodAllergy 5",
      description: "AI nutrition analyzer for food enthusiasts and professionals.",
      url: "https://example.com/foodallergy 5",
      tags: ["Nutrition", "Cooking"],
      icon: "🍲",
      color: ["#ef4444", "#b91c1c"],
      level: 3,
    },
    {
      title: "FoodAllergy 6",
      description: "AI meal planner for food enthusiasts and professionals.",
      url: "https://example.com/foodallergy 6",
      tags: ["Diet", "Food"],
      icon: "🍲",
      color: ["#0ea5e9", "#0284c7"],
      level: 1,
    },
    {
      title: "ChefBot 7",
      description: "AI shopping list maker for food enthusiasts and professionals.",
      url: "https://example.com/chefbot 7",
      tags: ["Recipes", "Nutrition"],
      icon: "🍲",
      color: ["#059669", "#047857"],
      level: 2,
    },
    {
      title: "DietGenie 8",
      description: "AI meal planner for food enthusiasts and professionals.",
      url: "https://example.com/dietgenie 8",
      tags: ["Diet", "Food"],
      icon: "🍲",
      color: ["#ef4444", "#b91c1c"],
      level: 4,
    },
    {
      title: "ChefBot 9",
      description: "AI meal planner for food enthusiasts and professionals.",
      url: "https://example.com/chefbot 9",
      tags: ["Recipes", "Recipes"],
      icon: "🍲",
      color: ["#ef4444", "#b91c1c"],
      level: 1,
    },
    {
      title: "DietGenie 10",
      description: "AI nutrition analyzer for food enthusiasts and professionals.",
      url: "https://example.com/dietgenie 10",
      tags: ["Diet", "Nutrition"],
      icon: "🍲",
      color: ["#2e7d32", "#1b5e20"],
      level: 4,
    },
    {
      title: "FoodAllergy 11",
      description: "AI recipe generator for food enthusiasts and professionals.",
      url: "https://example.com/foodallergy 11",
      tags: ["Recipes", "Nutrition"],
      icon: "🍲",
      color: ["#2e7d32", "#1b5e20"],
      level: 3,
    },
    {
      title: "RecipeAI 12",
      description: "AI recipe generator for food enthusiasts and professionals.",
      url: "https://example.com/recipeai 12",
      tags: ["Diet", "Food"],
      icon: "🍲",
      color: ["#0ea5e9", "#0284c7"],
      level: 3,
    },
    {
      title: "FoodAllergy 13",
      description: "AI recipe generator for food enthusiasts and professionals.",
      url: "https://example.com/foodallergy 13",
      tags: ["Diet", "Nutrition"],
      icon: "🍲",
      color: ["#1976d2", "#0d47a1"],
      level: 3,
    },
    {
      title: "NutritionScan 14",
      description: "AI shopping list maker for food enthusiasts and professionals.",
      url: "https://example.com/nutritionscan 14",
      tags: ["Cooking", "Food"],
      icon: "🍲",
      color: ["#4285f4", "#34a853"],
      level: 1,
    },
    {
      title: "FoodAllergy 15",
      description: "AI recipe generator for food enthusiasts and professionals.",
      url: "https://example.com/foodallergy 15",
      tags: ["Recipes", "Food"],
      icon: "🍲",
      color: ["#2e7d32", "#1b5e20"],
      level: 1,
    },
    {
      title: "NutritionScan 16",
      description: "AI diet advisor for food enthusiasts and professionals.",
      url: "https://example.com/nutritionscan 16",
      tags: ["Nutrition", "Diet"],
      icon: "🍲",
      color: ["#ef4444", "#b91c1c"],
      level: 3,
    },
    {
      title: "CookAssist 17",
      description: "AI diet advisor for food enthusiasts and professionals.",
      url: "https://example.com/cookassist 17",
      tags: ["Recipes", "Nutrition"],
      icon: "🍲",
      color: ["#ec4899", "#db2777"],
      level: 4,
    },
    {
      title: "RecipeAI 18",
      description: "AI recipe generator for food enthusiasts and professionals.",
      url: "https://example.com/recipeai 18",
      tags: ["Nutrition", "Cooking"],
      icon: "🍲",
      color: ["#ef4444", "#b91c1c"],
      level: 4,
    }
  ],
  gardening: [
    {
      title: "GardenPlan 0",
      description: "AI lawn care helper for gardening enthusiasts and professionals.",
      url: "https://example.com/gardenplan 0",
      tags: ["Plants", "Growing"],
      icon: "🌱",
      color: ["#ef4444", "#b91c1c"],
      level: 2,
    },
    {
      title: "PlantBot 1",
      description: "AI plant identifier for gardening enthusiasts and professionals.",
      url: "https://example.com/plantbot 1",
      tags: ["Growing", "Growing"],
      icon: "🌱",
      color: ["#059669", "#047857"],
      level: 3,
    },
    {
      title: "GardenPlan 2",
      description: "AI garden designer for gardening enthusiasts and professionals.",
      url: "https://example.com/gardenplan 2",
      tags: ["Gardening", "Plants"],
      icon: "🌱",
      color: ["#7c3aed", "#5b21b6"],
      level: 2,
    },
    {
      title: "HarvestAI 3",
      description: "AI garden designer for gardening enthusiasts and professionals.",
      url: "https://example.com/harvestai 3",
      tags: ["Plants", "Growing"],
      icon: "🌱",
      color: ["#0d9488", "#0f766e"],
      level: 4,
    },
    {
      title: "GardenAI 4",
      description: "AI garden designer for gardening enthusiasts and professionals.",
      url: "https://example.com/gardenai 4",
      tags: ["Outdoor", "Growing"],
      icon: "🌱",
      color: ["#2e7d32", "#1b5e20"],
      level: 3,
    },
    {
      title: "HarvestAI 5",
      description: "AI harvest planner for gardening enthusiasts and professionals.",
      url: "https://example.com/harvestai 5",
      tags: ["Growing", "Outdoor"],
      icon: "🌱",
      color: ["#2e7d32", "#1b5e20"],
      level: 3,
    },
    {
      title: "GrowAssist 6",
      description: "AI garden designer for gardening enthusiasts and professionals.",
      url: "https://example.com/growassist 6",
      tags: ["Growing", "Outdoor"],
      icon: "🌱",
      color: ["#ef4444", "#b91c1c"],
      level: 2,
    },
    {
      title: "GardenPlan 7",
      description: "AI lawn care helper for gardening enthusiasts and professionals.",
      url: "https://example.com/gardenplan 7",
      tags: ["Growing", "Plants"],
      icon: "🌱",
      color: ["#ec4899", "#db2777"],
      level: 4,
    },
    {
      title: "GardenPlan 8",
      description: "AI plant identifier for gardening enthusiasts and professionals.",
      url: "https://example.com/gardenplan 8",
      tags: ["Plants", "Growing"],
      icon: "🌱",
      color: ["#a855f7", "#7e22ce"],
      level: 4,
    },
    {
      title: "HarvestAI 9",
      description: "AI growing advisor for gardening enthusiasts and professionals.",
      url: "https://example.com/harvestai 9",
      tags: ["Plants", "Outdoor"],
      icon: "🌱",
      color: ["#059669", "#047857"],
      level: 3,
    },
    {
      title: "GardenPlan 10",
      description: "AI growing advisor for gardening enthusiasts and professionals.",
      url: "https://example.com/gardenplan 10",
      tags: ["Growing", "Gardening"],
      icon: "🌱",
      color: ["#4285f4", "#34a853"],
      level: 4,
    },
    {
      title: "SoilScan 11",
      description: "AI garden designer for gardening enthusiasts and professionals.",
      url: "https://example.com/soilscan 11",
      tags: ["Plants", "Plants"],
      icon: "🌱",
      color: ["#ec4899", "#db2777"],
      level: 4,
    },
    {
      title: "LawnCare 12",
      description: "AI harvest planner for gardening enthusiasts and professionals.",
      url: "https://example.com/lawncare 12",
      tags: ["Plants", "Growing"],
      icon: "🌱",
      color: ["#a855f7", "#7e22ce"],
      level: 3,
    }
  ],
};