/**
 * Niche AI — Curated AI tools for niche categories
 * Each item supports: title, description, url, tags, icon, color, level (1–10)
 */

const nicheData = {
  taxes: [
    { title: "TurboTax AI Assist", description: "AI-powered tax preparation with smart deduction finder and filing help.", url: "https://turbotax.intuit.com", tags: ["Filing", "Deductions", "Self-Employed"], icon: "\u{1F4B8}", color: ["#2e7d32", "#1b5e20"], level: 1 },
    { title: "H&R Block AI Tax Advisor", description: "Get answers to tax questions and maximize refunds with AI guidance.", url: "https://www.hrblock.com", tags: ["Filing", "Advisor", "Refunds"], icon: "\u{1F4CA}", color: ["#1976d2", "#0d47a1"], level: 1 },
    { title: "April", description: "AI tax assistant for freelancers and self-employed. Automates deductions.", url: "https://www.getapril.com", tags: ["Freelance", "Automation", "Deductions"], icon: "\u{1F4DD}", color: ["#7c3aed", "#5b21b6"], level: 2 },
    { title: "TaxGPT", description: "Chat-based tax Q&A for understanding deductions, credits, and rules.", url: "https://taxgpt.ai", tags: ["Q&A", "Education", "Credits"], icon: "\u{1F4AC}", color: ["#0d9488", "#0f766e"], level: 1 },
    { title: "FlyFin", description: "AI finds and tracks tax deductions for freelancers automatically.", url: "https://www.flyfin.tax", tags: ["Freelance", "1099", "Expense Tracking"], icon: "\u{1F4B0}", color: ["#ea580c", "#c2410c"], level: 2 },
  ],
  home: [
    { title: "Reimagine Home", description: "AI interior design. Upload a photo and get redesign suggestions.", url: "https://reimaginehome.ai", tags: ["Interior", "Design", "Visualization"], icon: "\u{1F3E0}", color: ["#a855f7", "#7e22ce"], level: 1 },
    { title: "ChatGPT (Recipes)", description: "Generate meal plans, recipes, and shopping lists tailored to your pantry.", url: "https://chat.openai.com", tags: ["Recipes", "Meal Plans", "Cooking"], icon: "\u{1F372}", color: ["#10a37f", "#1a7f5a"], level: 1 },
    { title: "Amazon Alexa", description: "AI voice assistant for smart home control, routines, and automation.", url: "https://alexa.amazon.com", tags: ["Smart Home", "Voice", "Automation"], icon: "\u{1F4E1}", color: ["#00a8e1", "#0077b6"], level: 1 },
    { title: "Google Home", description: "Control lights, thermostats, and devices with AI voice commands.", url: "https://home.google.com", tags: ["Smart Home", "Nest", "Voice"], icon: "\u{1F4F1}", color: ["#4285f4", "#34a853"], level: 1 },
    { title: "Replicate (Home Models)", description: "Run image-to-design, room staging, and renovation AI models.", url: "https://replicate.com", tags: ["API", "Design", "Staging"], icon: "\u{1F3A8}", color: ["#6366f1", "#4f46e5"], level: 5 },
  ],
  travel: [
    { title: "ChatGPT Travel Planner", description: "Plan itineraries, get local tips, and tailor trips to your preferences.", url: "https://chat.openai.com", tags: ["Itineraries", "Tips", "Custom"], icon: "\u{1F30D}", color: ["#10a37f", "#1a7f5a"], level: 1 },
    { title: "Perplexity Travel", description: "Research destinations with cited sources. Weather, visas, hotels.", url: "https://perplexity.ai", tags: ["Research", "Cited", "Real-time"], icon: "\u{1F50D}", color: ["#20b2aa", "#2980b9"], level: 1 },
    { title: "Wanderlog", description: "AI-assisted trip planning. Import bookings and get day-by-day plans.", url: "https://wanderlog.com", tags: ["Itinerary", "Collaborative", "Maps"], icon: "\u{1F5FA}\u{FE0F}", color: ["#059669", "#047857"], level: 1 },
    { title: "Hopper", description: "AI predicts flight and hotel prices. Know when to book.", url: "https://www.hopper.com", tags: ["Predictions", "Deals", "Flights"], icon: "\u{2708}\u{FE0F}", color: ["#ec4899", "#db2777"], level: 1 },
    { title: "Layla (TripAdvisor)", description: "AI travel advisor for personalized recommendations and bookings.", url: "https://www.tripadvisor.com", tags: ["Recommendations", "Hotels", "Reviews"], icon: "\u{1F6CF}\u{FE0F}", color: ["#00aa6c", "#008556"], level: 1 },
    { title: "Kayak AI", description: "Smart search and price alerts. AI explains fare changes.", url: "https://www.kayak.com", tags: ["Flights", "Price Alerts", "Deals"], icon: "\u{1F4B5}", color: ["#f59e0b", "#d97706"], level: 1 },
  ],
  books: [
    { title: "ChatGPT Book Recs", description: "Get personalized book recommendations based on tastes and mood.", url: "https://chat.openai.com", tags: ["Recommendations", "Personalized", "Genres"], icon: "\u{1F4DA}", color: ["#10a37f", "#1a7f5a"], level: 1 },
    { title: "Audible Plus", description: "AI-narrated audiobooks. Thousands of titles with natural-sounding voices.", url: "https://www.audible.com", tags: ["Audiobooks", "AI Narration", "TTS"], icon: "\u{1F50A}", color: ["#f59e0b", "#b45309"], level: 1 },
    { title: "Blinkist", description: "AI-powered summaries of nonfiction books. 15-minute key takeaways.", url: "https://www.blinkist.com", tags: ["Summaries", "Nonfiction", "Speed Reading"], icon: "\u{1F4D6}", color: ["#3b82f6", "#1d4ed8"], level: 1 },
    { title: "Goodreads AI", description: "Personalized recommendations and reading challenges powered by ML.", url: "https://www.goodreads.com", tags: ["Recommendations", "Reviews", "Social"], icon: "\u{2764}\u{FE0F}", color: ["#553c9a", "#44337a"], level: 1 },
    { title: "Summarize.tech", description: "Summarize long articles and PDFs. Great for research and textbooks.", url: "https://www.summarize.tech", tags: ["Summaries", "PDF", "Research"], icon: "\u{1F4C4}", color: ["#0ea5e9", "#0284c7"], level: 2 },
    { title: "Google Play Books", description: "Read aloud, translate, and lookup definitions with AI assistance.", url: "https://play.google.com/books", tags: ["E-reader", "TTS", "Translation"], icon: "\u{1F4D5}", color: ["#4285f4", "#34a853"], level: 1 },
  ],
  media: [
    { title: "Descript", description: "Edit video and podcast by editing text. AI voices and transcription.", url: "https://www.descript.com", tags: ["Video", "Podcast", "Transcription"], icon: "\u{1F3AC}", color: ["#ec4899", "#be185d"], level: 3 },
    { title: "Runway", description: "AI video editing: green screen, motion tracking, and generative effects.", url: "https://runwayml.com", tags: ["Video", "VFX", "Generative"], icon: "\u{1F4F9}", color: ["#8b5cf6", "#6d28d9"], level: 4 },
    { title: "CapCut", description: "AI-powered cuts, captions, and effects for short-form video.", url: "https://www.capcut.com", tags: ["Video", "Short-form", "TikTok"], icon: "\u{1F4FA}", color: ["#ef4444", "#b91c1c"], level: 2 },
    { title: "Adobe Firefly", description: "Generate images, vectors, and edits. Ethical, licensed training.", url: "https://www.adobe.com/products/firefly.html", tags: ["Image", "Design", "Adobe"], icon: "\u{1F525}", color: ["#ff3366", "#cc2952"], level: 2 },
    { title: "Canva AI", description: "Magic Design, background removal, text-to-image for presentations.", url: "https://www.canva.com", tags: ["Design", "Templates", "Social"], icon: "\u{1F3A8}", color: ["#00c4cc", "#0099a0"], level: 1 },
    { title: "Luminar Neo", description: "AI photo editing: sky replacement, portrait enhancement, one-click fixes.", url: "https://skylum.com/luminar", tags: ["Photo", "Retouching", "Landscape"], icon: "\u{1F4F8}", color: ["#0ea5e9", "#0369a1"], level: 3 },
    { title: "Pika Labs", description: "AI video generation from text and image prompts.", url: "https://pika.art", tags: ["Video", "Generation", "Creative"], icon: "\u{1F3A5}", color: ["#8b5cf6", "#7c3aed"], level: 3 },
  ],
  entertainment: [
    { title: "Suno", description: "Create full songs from text prompts. AI music generation.", url: "https://suno.com", tags: ["Music", "Generation", "Songs"], icon: "\u{1F3B5}", color: ["#f97316", "#ea580c"], level: 1 },
    { title: "Udio", description: "AI music creation. Generate tracks in any style or genre.", url: "https://www.udio.com", tags: ["Music", "Generation", "Genres"], icon: "\u{1F3BA}", color: ["#6366f1", "#4f46e5"], level: 1 },
    { title: "ChatGPT Movie Recs", description: "Get movie and TV recommendations based on mood and preferences.", url: "https://chat.openai.com", tags: ["Movies", "TV", "Recommendations"], icon: "\u{1F3AC}", color: ["#10a37f", "#1a7f5a"], level: 1 },
    { title: "Midjourney", description: "Generate art for album covers, posters, and creative projects.", url: "https://midjourney.com", tags: ["Art", "Generation", "Creative"], icon: "\u{1F3A8}", color: ["#e44d8a", "#b83280"], level: 2 },
    { title: "Character.AI", description: "Chat with AI characters. Roleplay, storytelling, and fun.", url: "https://character.ai", tags: ["Chat", "Roleplay", "Characters"], icon: "\u{1F9DE}", color: ["#8b5cf6", "#7c3aed"], level: 1 },
    { title: "Inworld", description: "Create AI NPCs for games. Conversational, emotionally intelligent.", url: "https://www.inworld.ai", tags: ["Gaming", "NPCs", "Conversational"], icon: "\u{1F3AE}", color: ["#06b6d4", "#0891b2"], level: 5 },
  ],
  sports: [
    { title: "ChatGPT Sports Analysis", description: "Get stats, predictions, and breakdowns. Fantasy and betting insights.", url: "https://chat.openai.com", tags: ["Analysis", "Stats", "Fantasy"], icon: "\u{26BD}", color: ["#10a37f", "#1a7f5a"], level: 1 },
    { title: "ESPN Fantasy", description: "AI-powered projections, lineup optimizers, and waiver suggestions.", url: "https://fantasy.espn.com", tags: ["Fantasy", "Football", "Basketball"], icon: "\u{1F3C8}", color: ["#dc2626", "#b91c1c"], level: 2 },
    { title: "Whoop", description: "AI recovery and strain analysis. Optimize training and sleep.", url: "https://www.whoop.com", tags: ["Fitness", "Recovery", "Wearable"], icon: "\u{1F3CB}\u{FE0F}", color: ["#000000", "#374151"], level: 2 },
    { title: "HomeCourt", description: "AI basketball trainer. Tracks shots, drills, and improvement over time.", url: "https://www.homecourt.ai", tags: ["Basketball", "Training", "Tracking"], icon: "\u{1F3C0}", color: ["#f59e0b", "#d97706"], level: 2 },
    { title: "Zwift", description: "AI-paced cycling and running. Virtual worlds and structured workouts.", url: "https://www.zwift.com", tags: ["Cycling", "Running", "Indoor"], icon: "\u{1F3C4}", color: ["#22c55e", "#16a34a"], level: 2 },
  ],
  health: [
    { title: "Nobu", description: "AI mental health and wellness app. Coping skills, mindfulness, journaling, mood tracking.", url: "https://nobu.ai", tags: ["Mental Health", "Wellness", "Mindfulness"], icon: "\u{1F9E1}", color: ["#6366f1", "#4f46e5"], level: 1 },
    { title: "Headspace (Ebb)", description: "Empathetic AI companion. Guided self-reflection and meditation recommendations.", url: "https://www.headspace.com", tags: ["Meditation", "Mindfulness", "Emotional"], icon: "\u{1F31F}", color: ["#10b981", "#059669"], level: 1 },
    { title: "ChatGPT Health Q&A", description: "General health information and wellness guidance. Not a substitute for medical advice.", url: "https://chat.openai.com", tags: ["Q&A", "Wellness", "Education"], icon: "\u{1F9FA}", color: ["#10a37f", "#1a7f5a"], level: 1 },
    { title: "Perplexity Health", description: "Research health topics with cited sources. Always verify with professionals.", url: "https://perplexity.ai", tags: ["Research", "Cited", "Medical"], icon: "\u{1F50D}", color: ["#20b2aa", "#2980b9"], level: 1 },
    { title: "Apple Health + AI", description: "Health insights, trends, and summaries powered by on-device ML.", url: "https://www.apple.com/health", tags: ["Fitness", "Sleep", "Tracking"], icon: "\u{1F4DD}", color: ["#555555", "#333333"], level: 2 },
  ],
  education: [
    { title: "Khanmigo (Khan Academy)", description: "AI tutor that guides with Socratic questioning. Math, science, test prep.", url: "https://www.khanacademy.org", tags: ["Tutoring", "Math", "K-12"], icon: "\u{1F392}", color: ["#14b8a6", "#0d9488"], level: 1 },
    { title: "ChatGPT Tutoring", description: "Explain concepts, debug code, practice languages, and quiz yourself.", url: "https://chat.openai.com", tags: ["Tutoring", "Explanation", "Practice"], icon: "\u{1F4AC}", color: ["#10a37f", "#1a7f5a"], level: 1 },
    { title: "Duolingo Max", description: "AI-powered language learning. Roleplay, explanations, and personalized feedback.", url: "https://www.duolingo.com", tags: ["Languages", "Gamified", "Speaking"], icon: "\u{1F1FA}\u{1F1F8}", color: ["#58cc02", "#1cb0f6"], level: 1 },
    { title: "Quizlet AI", description: "AI-generated flashcards, quizzes, and study guides from your materials.", url: "https://quizlet.com", tags: ["Flashcards", "Study", "Quizzes"], icon: "\u{1F4D6}", color: ["#4255ff", "#2e3856"], level: 1 },
    { title: "Notion AI", description: "Summarize notes, generate study guides, and clarify concepts in your workspace.", url: "https://www.notion.so", tags: ["Notes", "Summaries", "Study"], icon: "\u{1F4DD}", color: ["#000000", "#37352f"], level: 2 },
    { title: "Khan Academy in ChatGPT", description: "Generate standards-aligned math problems and practice in ChatGPT.", url: "https://chat.openai.com", tags: ["Math", "K-12", "Standards"], icon: "\u{1F4DA}", color: ["#10a37f", "#1a7f5a"], level: 1 },
  ],
  finance: [
    { title: "Monarch Money", description: "AI learns spending habits and organizes transactions. Net worth tracking.", url: "https://www.monarchmoney.com", tags: ["Budget", "Tracking", "Net Worth"], icon: "\u{1F4B8}", color: ["#7c3aed", "#5b21b6"], level: 2 },
    { title: "YNAB", description: "AI-powered budgeting with envelope system and expense forecasting.", url: "https://www.youneedabudget.com", tags: ["Budget", "Goals", "Zero-Based"], icon: "\u{1F4CA}", color: ["#0d9488", "#0f766e"], level: 2 },
    { title: "Origin", description: "AI budgeting, portfolio tracking, tax filing. Forbes Best Budgeting App 2024.", url: "https://useorigin.com", tags: ["Budget", "Investing", "Tax"], icon: "\u{1F4B0}", color: ["#0ea5e9", "#0284c7"], level: 2 },
    { title: "Wealthfront", description: "AI-managed investing. Tax-loss harvesting and personalized allocation.", url: "https://www.wealthfront.com", tags: ["Investing", "Robo-Advisor", "Tax"], icon: "\u{1F4B9}", color: ["#00c805", "#00a805"], level: 2 },
    { title: "Betterment", description: "AI investing with goal-based portfolios and automated rebalancing.", url: "https://www.betterment.com", tags: ["Investing", "Goals", "Automation"], icon: "\u{1F4B5}", color: ["#00b894", "#00a884"], level: 2 },
  ],
  legal: [
    { title: "ChatGPT Legal Q&A", description: "General legal Q&A for understanding concepts. Not legal advice.", url: "https://chat.openai.com", tags: ["Q&A", "Education", "Concepts"], icon: "\u{1F4AC}", color: ["#10a37f", "#1a7f5a"], level: 1 },
    { title: "Ironclad AI", description: "AI contract analysis with redline suggestions and data extraction.", url: "https://ironcladapp.com", tags: ["Contracts", "Analysis", "Redlining"], icon: "\u{2696}\u{FE0F}", color: ["#6366f1", "#4f46e5"], level: 5 },
    { title: "LexCheck", description: "AI contract review with Microsoft Word integration. Fast turnaround.", url: "https://lexcheck.com", tags: ["Contracts", "Word", "Enterprise"], icon: "\u{1F4DD}", color: ["#0d9488", "#0f766e"], level: 4 },
    { title: "Harvey AI", description: "AI for legal research, drafting, and contract analysis.", url: "https://www.harvey.ai", tags: ["Legal Research", "Drafting", "Analysis"], icon: "\u{1F4DA}", color: ["#1e3a5f", "#0f2744"], level: 6 },
    { title: "Casetext (CoCounsel)", description: "AI legal assistant for research, document review, and deposition prep.", url: "https://casetext.com", tags: ["Research", "Review", "Litigation"], icon: "\u{1F4C4}", color: ["#1976d2", "#0d47a1"], level: 5 },
  ],
  pets: [
    { title: "TTcare (AI FOR PET)", description: "AI health scanning for eyes, skin, teeth, joints. Share data with vets.", url: "https://www.ttcare.com.tw", tags: ["Health Scan", "Veterinary", "CES Award"], icon: "\u{1F436}", color: ["#f59e0b", "#d97706"], level: 2 },
    { title: "PawSmart.AI", description: "Real-time pet health monitoring. 97% accuracy, instant vet access.", url: "https://pawsmart.ai", tags: ["Monitoring", "Health", "Vets"], icon: "\u{1F43E}", color: ["#059669", "#047857"], level: 2 },
    { title: "ChatGPT Pet Q&A", description: "General pet care, breed info, and training tips. Supplement vet advice.", url: "https://chat.openai.com", tags: ["Q&A", "Training", "Care"], icon: "\u{1F4AC}", color: ["#10a37f", "#1a7f5a"], level: 1 },
    { title: "PetDesk", description: "AI-powered vet communication. Appointments, reminders, health records.", url: "https://www.petdesk.com", tags: ["Veterinary", "Appointments", "Records"], icon: "\u{1F4F1}", color: ["#6366f1", "#4f46e5"], level: 2 },
  ],
  food: [
    { title: "ChefGPT", description: "AI recipes from ingredients, meal plans, shopping lists. 1M+ users.", url: "https://chefgpt.xyz", tags: ["Recipes", "Meal Plans", "Pantry"], icon: "\u{1F372}", color: ["#ea580c", "#c2410c"], level: 1 },
    { title: "Ollie", description: "AI meal planning based on preferences, diet, skill level, and schedule.", url: "https://ollie.ai", tags: ["Meal Planning", "Grocery", "Family"], icon: "\u{1F958}", color: ["#059669", "#047857"], level: 1 },
    { title: "ChatGPT Recipes", description: "Recipe ideas, substitutions, nutrition info, and cooking tips.", url: "https://chat.openai.com", tags: ["Recipes", "Substitutions", "Tips"], icon: "\u{1F4AC}", color: ["#10a37f", "#1a7f5a"], level: 1 },
    { title: "Strongr Fastr", description: "AI meal plans for fitness goals. Macros, dietary needs, budget.", url: "https://strongrfastr.com", tags: ["Nutrition", "Fitness", "Macros"], icon: "\u{1F3CB}\u{FE0F}", color: ["#3b82f6", "#1d4ed8"], level: 2 },
  ],
  gardening: [
    { title: "PlantNet", description: "Crowd-sourced plant ID. 20,000+ species. Free and accurate.", url: "https://identify.plantnet.org", tags: ["Identification", "Botany", "Community"], icon: "\u{1F331}", color: ["#22c55e", "#16a34a"], level: 1 },
    { title: "Florify", description: "33,000+ plant species, disease diagnosis, AI care expert.", url: "https://florify.app", tags: ["Identification", "Care", "Disease"], icon: "\u{1F337}", color: ["#ec4899", "#db2777"], level: 2 },
    { title: "Plantora", description: "Plant ID, disease diagnosis, symptom checker. Free with expert access.", url: "https://plantora.app", tags: ["Identification", "Disease", "Care"], icon: "\u{1F33F}", color: ["#059669", "#047857"], level: 1 },
    { title: "From Seed to Spoon", description: "Planting dates, companion planting, pest/disease ID, organic treatments.", url: "https://www.fromseedtospoon.com", tags: ["Planning", "Companion", "Organic"], icon: "\u{1F331}", color: ["#2e7d32", "#1b5e20"], level: 2 },
  ],
  realEstate: [
    { title: "Zillow Zestimate", description: "AI-powered home valuation. Sub-1.9% error for off-market homes.", url: "https://www.zillow.com", tags: ["Valuation", "AVM", "Listings"], icon: "\u{1F3E1}", color: ["#006aff", "#0052cc"], level: 1 },
    { title: "Redfin Estimate", description: "AVM with confidence scores. Property data and market trends.", url: "https://www.redfin.com", tags: ["Valuation", "Market", "Tours"], icon: "\u{1F3E0}", color: ["#a02024", "#7a181b"], level: 1 },
    { title: "HouseCanary", description: "1,000+ data points per property. Valuation, rental analysis, forecasting.", url: "https://www.housecanary.com", tags: ["Valuation", "Rental", "Enterprise"], icon: "\u{1F4CA}", color: ["#0d9488", "#0f766e"], level: 5 },
    { title: "Perplexity Real Estate", description: "Research neighborhoods, schools, and market trends with citations.", url: "https://perplexity.ai", tags: ["Research", "Neighborhoods", "Schools"], icon: "\u{1F50D}", color: ["#20b2aa", "#2980b9"], level: 1 },
  ],
  career: [
    { title: "LinkedIn AI Job Coach", description: "Resume feedback, cover letters, conversational job search. Premium feature.", url: "https://www.linkedin.com", tags: ["Resume", "Cover Letter", "Jobs"], icon: "\u{1F4BC}", color: ["#0a66c2", "#004182"], level: 1 },
    { title: "Indeed Career Scout", description: "AI job search: recommendations, resume optimization, mock interviews.", url: "https://www.indeed.com", tags: ["Jobs", "Resume", "Interviews"], icon: "\u{1F50D}", color: ["#2164f3", "#1a4fc4"], level: 1 },
    { title: "ChatGPT Resume & Cover Letter", description: "Tailor resumes to job descriptions. Draft cover letters and follow-ups.", url: "https://chat.openai.com", tags: ["Resume", "Cover Letter", "ATS"], icon: "\u{1F4AC}", color: ["#10a37f", "#1a7f5a"], level: 1 },
    { title: "Microsoft Copilot Resume", description: "Optimize resumes for ATS. Keyword integration from job descriptions.", url: "https://copilot.microsoft.com", tags: ["Resume", "ATS", "Keywords"], icon: "\u{1F4DD}", color: ["#00a4ef", "#0078d4"], level: 1 },
  ],
  automotive: [
    { title: "Car AI", description: "AI mechanic trained on your manual. Fuel tracking, recalls, service reminders.", url: "https://getcarai.com", tags: ["Maintenance", "Manuals", "Tracking"], icon: "\u{1F697}", color: ["#3b82f6", "#1d4ed8"], level: 2 },
    { title: "AI Car Pro", description: "Fuel, costs, mileage. Smart reminders. AI assistant for service questions.", url: "https://aicarpro.app", tags: ["Tracking", "Maintenance", "Costs"], icon: "\u{1F69C}", color: ["#059669", "#047857"], level: 2 },
    { title: "ChatGPT Car Q&A", description: "Maintenance tips, troubleshooting, car buying research.", url: "https://chat.openai.com", tags: ["Q&A", "Maintenance", "Research"], icon: "\u{1F4AC}", color: ["#10a37f", "#1a7f5a"], level: 1 },
    { title: "Carly", description: "AI fault identification from symptoms. Repair cost estimates from 60M records.", url: "https://www.mycarly.com", tags: ["Diagnostics", "Repairs", "Costs"], icon: "\u{1F527}", color: ["#ef4444", "#b91c1c"], level: 2 },
  ],
  writing: [
    { title: "Grammarly", description: "Grammar, clarity, proofreading. Real-time editing across platforms.", url: "https://www.grammarly.com", tags: ["Grammar", "Proofreading", "Clarity"], icon: "\u{270F}\u{FE0F}", color: ["#15c39a", "#0da88a"], level: 1 },
    { title: "Jasper", description: "Long-form content, marketing copy. Brand voice, templates, plagiarism check.", url: "https://www.jasper.ai", tags: ["Marketing", "Blogs", "Brand Voice"], icon: "\u{1F4DD}", color: ["#000000", "#333333"], level: 3 },
    { title: "Copy.ai", description: "Quick short-form content. Social posts, ads, email. Fast generation.", url: "https://www.copy.ai", tags: ["Social", "Ads", "Email"], icon: "\u{1F4E2}", color: ["#6366f1", "#4f46e5"], level: 2 },
    { title: "ChatGPT Writing", description: "Draft, edit, brainstorm. Any format from blog posts to scripts.", url: "https://chat.openai.com", tags: ["Drafting", "Editing", "Brainstorm"], icon: "\u{1F4AC}", color: ["#10a37f", "#1a7f5a"], level: 1 },
    { title: "Claude Writing", description: "Long-form writing, nuanced edits. Strong at tone and structure.", url: "https://claude.ai", tags: ["Long-form", "Editing", "Nuance"], icon: "\u{1F4DA}", color: ["#d97706", "#b45309"], level: 2 },
  ],
  marketing: [
    { title: "Jasper", description: "AI marketing copy. Ads, blogs, emails. Brand voice and templates.", url: "https://www.jasper.ai", tags: ["Copy", "Ads", "Blogs"], icon: "\u{1F4DD}", color: ["#000000", "#333333"], level: 3 },
    { title: "Copy.ai", description: "Social content, ad copy, sales emails. Fast generation.", url: "https://www.copy.ai", tags: ["Social", "Ads", "Sales"], icon: "\u{1F4E2}", color: ["#6366f1", "#4f46e5"], level: 2 },
    { title: "Canva AI", description: "Magic Design, text-to-image, background removal. Marketing visuals.", url: "https://www.canva.com", tags: ["Design", "Social", "Visuals"], icon: "\u{1F3A8}", color: ["#00c4cc", "#0099a0"], level: 1 },
    { title: "Hootsuite AI", description: "AI content ideas, best time to post, sentiment analysis.", url: "https://www.hootsuite.com", tags: ["Social", "Scheduling", "Analytics"], icon: "\u{1F4E1}", color: ["#ff7a59", "#e85d3a"], level: 2 },
  ],
};
